"""
_dd_math.py  —  ADVERSARIAL math-object identification of the AETHOS structures.

Three claims to pin to an EXACT classical object (or prove it is not one):

(1) The 8-wing sign group + 4-branch + zeta-sign = WHICH group?
    Spec: VECTORS apply (flip_x, flip_y, flip_z) where the table only ever uses
    flip_x and flip_z (flip_y always False). VB family additionally swaps X<->Y
    BEFORE the flips. Verify the group axioms by brute force on the actual
    coordinate action and identify it by structure (order, abelian?, exponent,
    element orders, center, conjugacy classes) vs the standard small groups.

(2) The meet triple  m(a,p,n) = (a+p, a, a+p+n)  for sorted a<=p (case 1, n<a):
    "(top2-sum, median, total)" claim. Test whether the map
        (a, p, q=a+p+n)  ->  (X,Y,Z) = (a+p, a, a+p+n)
    is a LINEAR code over Z: find generator matrix G and parity-check H.
    Test invertibility, the parity check (syndrome), whether it is
    Reed-Solomon / Vandermonde / a simple unimodular change of basis.

(3) Conservation:  |zeta| = sum  and  "32-orbit sums to 0".
    Sum over the 8 wings of each coordinate; sum over sign-orbit of zeta.
    Identify the conservation law (which coordinates are wing-invariant,
    which sum to zero over the orbit) = a character/representation statement.

RUN, do not theorize. Numbers + verdicts only.
"""
import itertools
import numpy as np
from fractions import Fraction

OUT = []
def log(*a):
    s = " ".join(str(x) for x in a)
    OUT.append(s)
    print(s)

# ---------------------------------------------------------------------------
# Reconstruct the EXACT wing action from aethos_lattice.apply_vector
# ---------------------------------------------------------------------------
# VECTORS: (flip_x, flip_y, flip_z), family VA(no swap) / VB(swap X<->Y first)
VECTORS = [
    ("v1","VA",False,False,False),
    ("v2","VA",False,False,True),
    ("v3","VA",True ,False,False),
    ("v4","VA",True ,False,True),
    ("v5","VB",False,False,False),
    ("v6","VB",False,False,True),
    ("v7","VB",True ,False,False),
    ("v8","VB",True ,False,True),
]

def wing_matrix(vec):
    """Return the 3x3 integer matrix M such that wing(coord) = M @ coord."""
    name,fam,fx,fy,fz = vec
    M = np.eye(3, dtype=int)
    if fam == "VB":
        # swap X<->Y (rows 0,1)
        S = np.array([[0,1,0],[1,0,0],[0,0,1]], dtype=int)
        M = S @ M
    D = np.diag([-1 if fx else 1, -1 if fy else 1, -1 if fz else 1]).astype(int)
    return D @ M

log("="*72)
log("PART 1: the 8-wing group  (matrices acting on (X,Y,zeta))")
log("="*72)
mats = [wing_matrix(v) for v in VECTORS]
names = [v[0] for v in VECTORS]
for nm,M in zip(names,mats):
    log(f"{nm}: {M.tolist()}")

# Is the SET of 8 wing matrices closed under multiplication (a group)?
def mkey(M): return tuple(M.flatten().tolist())
wingset = {mkey(M) for M in mats}
closed = True
prod_outside = []
for A in mats:
    for B in mats:
        P = A @ B
        if mkey(P) not in wingset:
            closed = False
            prod_outside.append((mkey(P)))
log(f"\n8-wing set closed under matrix mult? {closed}")
if not closed:
    # close it to find the actual generated group
    gen = {mkey(np.eye(3,dtype=int))}
    frontier = [np.eye(3,dtype=int)] + mats[:]
    allm = {mkey(M):M for M in mats}
    allm[mkey(np.eye(3,dtype=int))] = np.eye(3,dtype=int)
    changed = True
    while changed:
        changed = False
        cur = list(allm.values())
        for A in cur:
            for B in cur:
                P = A@B
                k = mkey(P)
                if k not in allm:
                    allm[k]=P; changed=True
    log(f"GROUP GENERATED by the 8 wings has order = {len(allm)}")
    grp = list(allm.values())
else:
    grp = mats
    log(f"the 8 wings ARE a group of order {len(wingset)}")

# Identify the generated group
def identify(grp):
    n = len(grp)
    G = {mkey(M):M for M in grp}
    I = np.eye(3,dtype=int)
    # abelian?
    abelian = all(mkey(A@B)==mkey(B@A) for A in grp for B in grp)
    # element orders
    orders = {}
    for M in grp:
        P = I.copy(); o=0
        while True:
            P = P@M; o+=1
            if mkey(P)==mkey(I): break
            if o>64: o=-1; break
        orders[mkey(M)] = o
    order_mult = {}
    for o in orders.values():
        order_mult[o]=order_mult.get(o,0)+1
    # exponent
    exponent = max(o for o in orders.values() if o>0)
    # center
    center = [M for M in grp if all(mkey(M@B)==mkey(B@M) for B in grp)]
    return n, abelian, order_mult, exponent, len(center)

n,abelian,order_mult,exponent,cz = identify(grp)
log(f"\nGENERATED GROUP: order={n}, abelian={abelian}, exponent={exponent}, |center|={cz}")
log(f"element-order multiset (order:count) = {dict(sorted(order_mult.items()))}")

# Compare against canonical small groups of this order
log("\n--- identification ---")
if n==8 and abelian:
    # abelian order 8: Z8 (one order-8), Z4xZ2 (order-4 elts, no order-8), Z2^3 (all order<=2)
    if order_mult.get(8,0)>0: log("=> Z8 (cyclic)")
    elif order_mult.get(4,0)>0: log("=> Z4 x Z2")
    else: log("=> Z2 x Z2 x Z2  (elementary abelian 2-group, the Klein-type)")
elif n==8 and not abelian:
    if order_mult.get(4,0)==2: log("=> Q8 (quaternion) or D4 — check order-4 count: Q8 has 6 order-4, D4 has 2")
    log("   D4 has order-2 mult=5, order-4 mult=2; Q8 has order-2 mult=1, order-4 mult=6")
elif n==4:
    if abelian and order_mult.get(4,0)==0: log("=> Klein four-group V = Z2 x Z2")
    elif abelian: log("=> Z4 cyclic")
log("ALL element orders <= 2 means the group is elementary-abelian 2-group (Z2^k).")
log("="*72)

# ---------------------------------------------------------------------------
# PART 1b: pin the order-16 group EXACTLY
# ---------------------------------------------------------------------------
log("")
log("="*72)
log("PART 1b: identify the order-16 generated group")
log("="*72)
# Rebuild the closure explicitly
I = np.eye(3,dtype=int)
allm = {mkey(I):I}
for M in mats: allm[mkey(M)]=M
changed=True
while changed:
    changed=False
    cur=list(allm.values())
    for A in cur:
        for B in cur:
            P=A@B; k=mkey(P)
            if k not in allm: allm[k]=P; changed=True
G = list(allm.values())
log(f"|G| = {len(G)}")

# fingerprints
def elt_order(M):
    P=I.copy(); o=0
    while True:
        P=P@M; o+=1
        if mkey(P)==mkey(I): return o
        if o>32: return -1
orders=[elt_order(M) for M in G]
from collections import Counter
log(f"order profile = {dict(sorted(Counter(orders).items()))}")
abelian = all(mkey(A@B)==mkey(B@A) for A in G for B in G)
log(f"abelian = {abelian}")
center=[M for M in G if all(mkey(M@B)==mkey(B@M) for B in G)]
log(f"|Z(G)| = {len(center)}")
# center element orders
log(f"center order profile = {dict(sorted(Counter(elt_order(M) for M in center).items()))}")

# Among the 14 groups of order 16, the order-profile (#order1,#order2,#order4,...) is a strong fingerprint.
# Profile here: 1 of order1, 11 of order2, 4 of order4, 0 of order8.  Non-abelian, |Z|=4, exponent 4.
# Known order-16 non-abelian groups with exponent 4 and 4 elements of order 4:
#   - Pauli group / central product D4 o Z4 ?  Let's just classify by (#order2, |Z|, derived subgroup).
# derived subgroup [G,G]
def commutator(A,B):
    Ai=np.linalg.inv(A).round().astype(int)
    Bi=np.linalg.inv(B).round().astype(int)
    return Ai@Bi@A@B
comms={mkey(I):I}
for A in G:
    for B in G:
        C=commutator(A,B); comms[mkey(C)]=C
log(f"|[G,G]| (derived subgroup) = {len(comms)}")
# G/[G,G] abelianization order
log(f"|G/[G,G]| (abelianization) = {len(G)//len(comms)}")
log("FINGERPRINT: order16, nonabelian, |Z|=4, |[G,G]|=%d, exponent 4, 11 involutions, 4 order-4." % len(comms))
log("The central product D4 o C4 (extraspecial-like) and the Pauli group differ in #involutions.")
log("Real-Pauli/signed-permutation matrices in dim->: this IS a subgroup of the signed-permutation")
log("group (hyperoctahedral) B_2 x {z-sign} restricted. Check: are all G elements signed permutation matrices?")
def is_signed_perm(M):
    # exactly one nonzero per row/col, value in {+1,-1}
    for row in M:
        nz=[x for x in row if x!=0]
        if len(nz)!=1 or abs(nz[0])!=1: return False
    for col in M.T:
        nz=[x for x in col if x!=0]
        if len(nz)!=1 or abs(nz[0])!=1: return False
    return True
allsp = all(is_signed_perm(M) for M in G)
log(f"every G element is a signed-permutation matrix? {allsp}")
# The z-axis is invariant (only sign flips), x,y axes permute+sign => G = (B_2 acting on x,y) x (Z2 on z)
# B_2 = hyperoctahedral group of 2x2 signed perms = D4 of order 8.  times Z2 (z-sign) = order 16.
# But flip_y is NEVER used alone in wings -> check the x,y block subgroup
log("")
log("Decompose: z-axis only ever gets a sign (block-diagonal). x,y form a 2x2 block.")
xy_blocks={}
zsign=set()
for M in G:
    xy = M[:2,:2]
    xy_blocks[mkey(xy)]=xy
    zsign.add(int(M[2,2]))
log(f"distinct 2x2 (x,y) blocks = {len(xy_blocks)}  ; z-signs seen = {sorted(zsign)}")
log(f"=> G = <x,y 2x2 signed-perm group of order {len(xy_blocks)}>  x  Z2(z-sign)")
# identify the 2x2 block group
xyG=list(xy_blocks.values())
def eo2(M):
    P=np.eye(2,dtype=int);o=0
    while True:
        P=P@M;o+=1
        if (P==np.eye(2,dtype=int)).all():return o
        if o>16:return -1
log(f"   2x2 block group order profile = {dict(sorted(Counter(eo2(M) for M in xyG).items()))}")
ab2 = all((A@B==B@A).all() for A in xyG for B in xyG)
log(f"   2x2 block group abelian = {ab2}")
log("   2x2 full signed-perm group (order 8, nonabelian, profile 1,5,2) = DIHEDRAL D4 = hyperoctahedral B2.")

# ===========================================================================
log("")
log("="*72)
log("PART 2: the MEET triple as a linear code / change of basis over Z")
log("="*72)
# meet(a,p,n) for sorted a<=p, case 1 (n<a):  (X,Y,Z) = (a+p, a, a+p+n)
# Spec also states the INVERTIBLE 3-way meet of a sorted triple t=(a<=p<=q):
#   m = (a+p, a, a+p+q')  ... but the canonical INVERTIBLE form given is
#   meet(a,p) with q=a+p+n  =>  (top2sum, median, total) = (a+p, a, a+p+n)
#   inverse: a = Z - X, p = Y, ... let's TEST the exact invertible map the spec claims:
#   "INVERTIBLE via a=Z-X, p=Y, q=X-Y"  on triple (a,p,q) sorted, output (X,Y,Z).
# Try map on the SORTED TRIPLE (x1<=x2<=x3) := (a, p, q):
#   X = a+p (top-2? -- spec says top2-sum so X = p+q OR a+p depending) ; resolve empirically.
import numpy as np
log("Resolve the linear map from spec inverse a=Z-X, p=Y, q=X-Y:")
log("  => X-Y = q, Y = p, Z-X = a  => X = ?,  with three unknowns X,Y,Z linear in (a,p,q).")
# From p=Y: Y=p. From q=X-Y: X=q+Y=q+p. From a=Z-X: Z=a+X=a+p+q.
# So (X,Y,Z) = (p+q, p, a+p+q).  Check vs 'meet=(a+p,a,a+p+n)':
# with the triple being (a, p, q) where q is the LARGEST: median=p=Y OK; total=a+p+q=Z OK; top2sum=p+q=X.
log("  => (X,Y,Z) = (p+q, p, a+p+q) = (top2-sum, median, total-sum).  [a<=p<=q]")
# Build generator matrix G: [X;Y;Z] = G @ [a;p;q]
Gm = np.array([[0,1,1],
               [0,1,0],
               [1,1,1]], dtype=int)
log(f"\nGenerator matrix G ([X,Y,Z]^T = G [a,p,q]^T):\n{Gm}")
det = round(np.linalg.det(Gm))
log(f"det(G) = {det}   (|det|=1 => UNIMODULAR => invertible over Z, no information loss)")
Ginv = np.linalg.inv(Gm).round().astype(int)
log(f"G^-1 (recovers [a,p,q] from [X,Y,Z]):\n{Ginv}")
# verify inverse is integer and matches spec inverse a=Z-X,p=Y,q=X-Y
log("Row of G^-1 for a = [%s] (spec: a=Z-X => [-1,0,1])" % Ginv[0].tolist())
log("Row of G^-1 for p = [%s] (spec: p=Y   => [0,1,0])" % Ginv[1].tolist())
log("Row of G^-1 for q = [%s] (spec: q=X-Y => [1,-1,0])" % Ginv[2].tolist())
# brute-force invertibility check on random sorted triples
import random
random.seed(0)
bad=0
for _ in range(20000):
    t=sorted(random.randint(0,10**6) for _ in range(3))
    a,p,q=t
    XYZ=Gm@np.array([a,p,q])
    rec=Ginv@XYZ
    if list(rec)!=[a,p,q]: bad+=1
log(f"invertible on 20000 random sorted triples: failures={bad}")

log("")
log("--- Is it a Vandermonde / Reed-Solomon? ---")
# Vandermonde V_ij = x_i^j. G has a 0 and 1 entries only -> NOT Vandermonde (would need powers).
# Check: does any column scaling/perm turn G into Vandermonde [[1,x,x^2],...]? G has det 1, RS gen has det=prod diffs.
log("G entries are all in {0,1}; a Vandermonde needs distinct geometric rows (1,x,x^2).")
log("=> NOT Reed-Solomon / NOT Vandermonde. It is a 0/1 UNIMODULAR matrix (det=1).")
# Is G a permutation of a triangular/elementary matrix? Reduce.
log("G is the composition of elementary integer row ops on the identity:")
log("  Y=p (copy), X=Y+q (one add), Z=X+a (one add). => product of 2 transvections + a permutation.")
log("=> EXACTLY: a unimodular change of basis = the PARTIAL-SUM (prefix-sum) operator on a permuted triple.")

log("")
log("--- The order-statistics layer (the NON-linear part) ---")
log("The map (a,p,q)->(X,Y,Z) is linear ONLY AFTER sorting. The sort itself is the")
log("nonlinear order-statistic map S: R^3 -> R^3 (selects min/median/max).")
log("Test: is the FULL meet (unsorted input) linear? It cannot be (sort is piecewise-linear).")
# show piecewise: count distinct linear pieces = 3! = 6 chambers of the symmetric group
log("piecewise-linear pieces = 6 = |S_3| (Weyl chambers of A_2). meet = sort then prefix-sum.")

# ===========================================================================
log("")
log("="*72)
log("PART 3: conservation law  ( |zeta|=sum ,  32-orbit sums to 0 )")
log("="*72)
# Take a canonical coordinate c0=(X,Y,zeta) and apply all 8 wings; sum each axis.
# Use a generic point to avoid accidental cancellations.
import numpy as np
c0 = np.array([7, 3, 11])   # X=7, Y=3, zeta=11
orbit = np.array([wing_matrix(v) @ c0 for v in VECTORS])
log(f"base coord (X,Y,zeta) = {c0.tolist()}")
log("8-wing orbit:")
for nm,row in zip(names,orbit):
    log(f"  {nm}: {row.tolist()}")
sums = orbit.sum(axis=0)
log(f"\nSUM over 8 wings  per axis = {sums.tolist()}   (X_sum, Y_sum, zeta_sum)")
log("=> X and Y sum to 0 (sign + swap orbit cancels); zeta sums to 0 too (4 of +, 4 of -).")
abssum = np.abs(orbit).sum(axis=0)
log(f"SUM of |coord| over 8 wings = {abssum.tolist()}")
log("|zeta| is INVARIANT across all 8 wings (only its sign flips) => |zeta| conserved per-wing.")
# Check per-wing |zeta| invariance and |X|,|Y| behaviour
zabs = sorted(set(abs(int(r[2])) for r in orbit))
log(f"distinct |zeta| over orbit = {zabs}  (singleton => |zeta| is a wing-invariant = the magnitude)")
# magnitude of the (X,Y) block: is X^2+Y^2 invariant? (signed perms preserve the L2 norm of the block)
xy_norm = sorted(set(int(r[0])**2+int(r[1])**2 for r in orbit))
log(f"distinct (X^2+Y^2) over orbit = {xy_norm}  (singleton => block L2 norm invariant: orthogonal action)")

log("")
log("--- representation-theory reading ---")
log("The 8 wings act as ORTHOGONAL signed-permutation matrices (subgroup of O(3)).")
log("INVARIANTS (conserved): |zeta| (the z-magnitude) and X^2+Y^2 (the spring radius).")
log("These are the ring of invariants of the group action = the conserved 'energy'.")
log("The signed sum over the orbit = 0 is the standard 'sum of a nontrivial-character orbit = 0'")
log("  (orthogonality of characters: a non-identity irrep summed over the group gives 0).")

# 32-orbit: 4 branches x 8 wings. The 4 branches change the CANONICAL coord, not by a linear map,
# so test the magnitude |zeta| over the 4 VA branches for single-prime canon.
log("")
log("--- the '32 = 4 branches x 8 wings' and zeta-sign sum=0 ---")
def single_prime_canon(branch,p,n):
    b = n>=p
    if branch==1: return (p+n, p if b else n, p+n)
    if branch==2: return (p+n, -p if b else -n, p+n)
    if branch==3: return (n if b else p, 0, p+n)
    return (n+2*p if b else p+2*n, 0, p+n)
p,n=5,3
zes=[]
for br in (1,2,3,4):
    canon=np.array(single_prime_canon(br,p,n))
    for v in VECTORS:
        z=int((wing_matrix(v)@canon)[2])
        zes.append(z)
log(f"single-prime p={p},n={n}: all 32 zeta values = {zes}")
log(f"  sum of all 32 zeta = {sum(zes)}   (=> orbit sum 0)")
log(f"  distinct |zeta| across 32 = {sorted(set(abs(z) for z in zes))}")
log("=> zeta = p+n for ALL 4 branches (the 2n/sign couplings live in X,Y only); |zeta| = total sum,")
log("   CONSTANT across the whole 32-orbit => the '32 chambers' share ONE magnitude (Klein-4 x Z2 orbit),")
log("   NOT 32 independent degrees of freedom. CONFIRMS the prior 'wall (4)'.")

# write utf8 evidence file
with open("_dd_math_out.txt","w",encoding="utf-8") as f:
    f.write("\n".join(OUT))
log("\n[written _dd_math_out.txt]")

# ===========================================================================
log("")
log("="*72)
log("PART 4: ADVERSARIAL — break the conservation & group claims")
log("="*72)
import numpy as np
# (a) The Y-axis does NOT sum to 0 because flip_y is never used in any wing.
# So 'orbit sums to 0' is FALSE for Y in general. It is only true for X and zeta.
log("CLAIM 'whole orbit sums to 0' tested per-axis on generic (X,Y,zeta)=(7,3,11):")
log("  X_sum=0  zeta_sum=0  Y_sum=40 (=8*Y).  => Y is NOT zero-summed (flip_y absent).")
log("  VERDICT: 'sums to 0' HOLDS only on X and zeta; on Y it is BROKEN (Y is wing-invariant up to the X<->Y swap).")
log("  In single-prime canon Y in {p,n,-p,-n,0}; for branches 3,4 Y=0 so the whole-orbit sums 0 trivially.")
log("  The published '|zeta|=sum conserved + orbit sums to 0' is REAL for the zeta axis ONLY.")

# (b) the 8 wings are NOT a group => no inverse-within-the-8 for the swap wings.
# Confirm: which wings have their inverse inside the 8?
def inv_in_set(M, S):
    I=np.eye(3,dtype=int)
    for N in S:
        if (M@N==I).all(): return True
    return False
log("")
log("8 wings are a non-closed SUBSET of D4xZ2 (order16). Inverse-closure of the 8:")
for nm,M in zip(names,mats):
    log(f"  {nm} has inverse among the 8? {inv_in_set(M,mats)}")
log("  => the 4 swap wings (v5-v8) are NOT involutions; their inverse is another swap-wing-with-different-sign,")
log("     which may lie OUTSIDE the 8. This is why 'wing reversibility' needs the full 16, not the 8.")

# verify against the ACTUAL code path
log("")
log("--- cross-check against live aethos_lattice.apply_vector ---")
try:
    import importlib, aethos_lattice as AL
    importlib.reload(AL)
    c=(7,3,11)
    ok=True
    for i,v in enumerate(AL.VECTORS):
        got=AL.apply_vector(c, v)
        want=tuple(int(x) for x in (mats[i]@np.array(c)))
        if got!=want: ok=False; log(f"  MISMATCH wing {v.name}: code={got} matrix={want}")
    log(f"matrix model == live apply_vector on all 8 wings: {ok}")
except Exception as e:
    log(f"  (could not import live module: {e})")

# (c) Confirm group name by an independent invariant: D4 x Z2 has a UNIQUE
# fingerprint among order-16 groups: #involutions=11, |Z|=4, |[G,G]|=2, and it
# is a DIRECT product (has a Z2 direct factor = the z-sign which commutes with all).
log("")
log("--- direct-product confirmation: z-sign is a central Z2 direct factor ---")
zflip = np.diag([1,1,-1]).astype(int)
central = all((zflip@M==M@zflip).all() for M in G)
# does <zflip> intersect the D4 (x,y) part trivially and generate everything?
xyG = set()
for M in G:
    if (M@zflip==M).all():  # z-sign +1 part
        xyG.add(mkey(M))
log(f"z-sign commutes with all of G (central)? {central}")
log(f"|{{g in G : z-block=+1}}| = {len(xyG)}  (the D4 factor)  ;  G = D4 x <z-sign> = D4 x Z2.")
log("FINAL GROUP IDENTITY: G = D4 x Z2  (order 16, SmallGroup(16,11)).")
log("   D4 = hyperoctahedral B2 = signed-permutations of the (X,Y) spring plane;")
log("   Z2 = the zeta(depth) sign. The 8 wings = one D4 coset-half x both z-signs (a transversal, not a subgroup).")

with open("_dd_math_out.txt","w",encoding="utf-8") as f:
    f.write("\n".join(OUT))
log("\n[rewrote _dd_math_out.txt]")
