#!/usr/bin/env python3
"""
Test 14 - "Few rules" reconstruction: the user's scheme, implemented literally.

The scheme as described:
  - a few tokens (3 seed primes) place the dots
  - each rotation moves 1 prime up  (chain index +1 per step, wing cycles 1..8)
  - the square root tells the meaning (byte extracted via isqrt of |Psi|^2 mix)
  - a frequency map assists reconstruction
  - claim: long strings reconstruct from just those few rules

We test this scheme honestly on three kinds of data:
  (A) Its OWN stream: data generated by the rules - does it reconstruct
      from a few tokens? (this is the strongest version of the claim)
  (B) Truly random data: how much does the rule-stream lock onto it,
      and what does the correction ledger cost?
  (C) Almost-rule data (rule stream + 5% noise): where is the boundary?
  (D) The frequency map: what it can and cannot save (it IS entropy coding)
  (E) Counting: how many "few-rule" programs exist vs how many strings
"""

from __future__ import annotations

import math
import random
import sys
import zlib
from collections import Counter
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from aethos_complex_plane import wing_transform
from aethos_lattice import BranchKind
from core.primes import chain_primes


def header(s: str):
    print()
    print("=" * 72)
    print(s)
    print("=" * 72)


def assertion(cond: bool, msg: str):
    print(f"  [{'PASS' if cond else 'FAIL'}]  {msg}")
    if not cond:
        sys.exit(1)


BASE = chain_primes(4300)


def rule_stream(seed_offsets: tuple[int, int, int], n_offset: int,
                length: int) -> bytes:
    """The user's scheme, literally.

    Start from 3 seed primes (given by offsets into the prime sequence).
    Each step: move every prime up by 1 (next prime), cycle the wing 1..8.
    The square root of the observable's norm extracts the byte meaning.
    """
    i0, i1, i2 = seed_offsets
    out = bytearray()
    for k in range(length):
        chain = (BASE[i0 + k], BASE[i1 + k], BASE[i2 + k])
        n = BASE[n_offset + k]
        wing = (k % 8) + 1
        psi = wing_transform(BranchKind.VA1, chain, n, wing)
        X, Y, Z = psi.coord
        meaning = math.isqrt(int(X * X + Y * Y + Z * Z))  # "square rooting tells its meaning"
        byte = (meaning + int(abs(X)) + 31 * int(abs(Z))) % 256
        out.append(byte)
    return bytes(out)


def correction_cost_bits(n_corrections: int, stream_len: int) -> float:
    """Cost to store a correction list: position + value per correction."""
    pos_bits = math.ceil(math.log2(max(stream_len, 2)))
    return n_corrections * (pos_bits + 8)


def main():
    header('"Few rules" reconstruction - seeds + rotation + sqrt, tested honestly')

    SEEDS = (0, 5, 11)   # 3 seed primes: BASE[0], BASE[5], BASE[11]
    N_OFF = 17
    LENGTH = 4096

    # ---------------------------------------------------------------
    # Part A: The scheme on its OWN stream - the claim's best case
    # ---------------------------------------------------------------
    print("\nPart A - Rule-born data: reconstruct 4096 bytes from a few tokens")
    print("-" * 72)

    stream = rule_stream(SEEDS, N_OFF, LENGTH)
    # The complete description: 3 seed offsets + n offset + length + wing rule
    # Generous accounting: 4 offsets x 2 bytes + length 2 bytes + 2 bytes rule id
    seed_token_bytes = 4 * 2 + 2 + 2
    regenerated = rule_stream(SEEDS, N_OFF, LENGTH)

    print(f"  stream length:        {len(stream)} bytes")
    print(f"  seed tokens:          {seed_token_bytes} bytes "
          f"(3 seed primes + n offset + length + rule)")
    print(f"  compression ratio:    {len(stream)/seed_token_bytes:.0f}x")
    assertion(regenerated == stream,
              "byte-exact reconstruction from seed tokens (replay the rules)")
    assertion(len(stream) / seed_token_bytes > 100,
              f"rule-born data compresses {len(stream)//seed_token_bytes}x - the claim is TRUE here")

    # And gzip can't see this structure at all:
    gz = zlib.compress(stream, 9)
    print(f"  gzip on same stream:  {len(gz)} bytes ({len(stream)/len(gz):.2f}x)")
    print(f"  -> the lattice description is {len(gz)//seed_token_bytes}x smaller than gzip's")

    # ---------------------------------------------------------------
    # Part B: Truly random data - how much does the rule stream lock on?
    # ---------------------------------------------------------------
    print("\nPart B - Random data: does the rotation stream lock onto it?")
    print("-" * 72)

    rnd = random.Random(424242)
    random_data = bytes(rnd.randrange(256) for _ in range(LENGTH))

    matches = sum(1 for a, b in zip(stream, random_data) if a == b)
    expected_chance = LENGTH / 256
    print(f"  bytes where rule-stream == random data: {matches} / {LENGTH}")
    print(f"  pure-chance expectation:                {expected_chance:.0f}")
    assertion(matches < expected_chance * 3,
              "rule stream matches random data only at chance level (no lock-on)")

    # The corrective codec: seeds + correction list for every miss
    misses = LENGTH - matches
    corr_bits = correction_cost_bits(misses, LENGTH)
    total_bytes = seed_token_bytes + corr_bits / 8
    print(f"\n  correction ledger for random data:")
    print(f"    seed tokens:        {seed_token_bytes} bytes")
    print(f"    corrections:        {misses} x (12+8 bits) = {corr_bits/8:.0f} bytes")
    print(f"    total:              {total_bytes:.0f} bytes vs original {LENGTH}")
    print(f"    ratio:              {total_bytes/LENGTH:.2f}x  (EXPANSION)")
    assertion(total_bytes > LENGTH,
              "random data EXPANDS under the scheme (corrections cost more than data)")

    # ---------------------------------------------------------------
    # Part C: Almost-rule data - the boundary made visible
    # ---------------------------------------------------------------
    print("\nPart C - Data that mostly follows the rules (5% noise)")
    print("-" * 72)

    noisy = bytearray(stream)
    n_flips = LENGTH * 5 // 100
    flip_positions = rnd.sample(range(LENGTH), n_flips)
    for pos in flip_positions:
        noisy[pos] = rnd.randrange(256)
    noisy = bytes(noisy)

    actual_misses = sum(1 for a, b in zip(stream, noisy) if a != b)
    corr_bits_c = correction_cost_bits(actual_misses, LENGTH)
    total_c = seed_token_bytes + corr_bits_c / 8
    gz_c = len(zlib.compress(noisy, 9))
    print(f"  noise injected:       {n_flips} positions (5%)")
    print(f"  actual mismatches:    {actual_misses}")
    print(f"  lattice codec total:  {total_c:.0f} bytes ({LENGTH/total_c:.1f}x compression)")
    print(f"  gzip:                 {gz_c} bytes ({LENGTH/gz_c:.2f}x)")
    assertion(total_c < LENGTH / 4,
              f"95%-rule data compresses {LENGTH/total_c:.0f}x via seeds+corrections")
    assertion(total_c < gz_c,
              "lattice codec beats gzip when data mostly follows the rules")

    # ---------------------------------------------------------------
    # Part D: The frequency map IS entropy coding (reaches H, never below)
    # ---------------------------------------------------------------
    print("\nPart D - The frequency map: what it saves and its hard floor")
    print("-" * 72)

    # Skewed (Zipf) data - the frequency map helps, down to entropy H
    n_sym = 8192
    weights = [1.0 / (i + 1) for i in range(256)]
    zipf_data = bytes(rnd.choices(range(256), weights=weights, k=n_sym))
    counts = Counter(zipf_data)
    H = -sum((c / n_sym) * math.log2(c / n_sym) for c in counts.values())
    ideal_bits = n_sym * H  # what a perfect frequency coder achieves
    zlib_bits = len(zlib.compress(zipf_data, 9)) * 8

    print(f"  Zipf data: {n_sym} bytes, empirical entropy H = {H:.2f} bits/byte")
    print(f"    perfect frequency coder:  {ideal_bits/8:.0f} bytes ({H:.2f} bits/byte - the floor)")
    print(f"    zlib actual:              {zlib_bits/8:.0f} bytes ({zlib_bits/n_sym:.2f} bits/byte)")
    assertion(zlib_bits >= ideal_bits * 0.95,
              "real coders sit AT or ABOVE the entropy floor, never below")

    # Uniform random data - the frequency map has nothing to grab
    counts_r = Counter(random_data)
    H_r = -sum((c / LENGTH) * math.log2(c / LENGTH) for c in counts_r.values())
    print(f"\n  random data: empirical entropy H = {H_r:.3f} bits/byte (max is 8.0)")
    print(f"    frequency-map headroom: {8 - H_r:.3f} bits/byte (~nothing)")
    assertion(H_r > 7.9,
              "uniform random bytes have ~8 bits/byte entropy - no frequency savings exist")

    # ---------------------------------------------------------------
    # Part E: Counting "few-rule" programs vs strings
    # ---------------------------------------------------------------
    print("\nPart E - How many few-rule descriptions exist?")
    print("-" * 72)

    # Generous rule space: 3 seed offsets (4300 choices each), n offset,
    # 8 wing phases, 256 rule variants
    rule_space = 4300 ** 3 * 4300 * 8 * 256
    rule_bits = math.log2(rule_space)
    string_bits = 8 * LENGTH
    print(f"  distinct few-rule programs:  ~2^{rule_bits:.0f}")
    print(f"  distinct 4096-byte strings:   2^{string_bits}")
    print(f"  coverage:                     2^-{string_bits - rule_bits:.0f} of all strings")
    print(f"\n  each rule-set replays exactly ONE string. With ~2^{rule_bits:.0f} rule-sets,")
    print(f"  the scheme can name ~2^{rule_bits:.0f} strings out of 2^{string_bits}. The rest -")
    print(f"  which is essentially ALL random data - has no few-rule description.")
    assertion(rule_bits < 64,
              "few-rule program space is tiny vs string space (Kolmogorov counting)")

    # ---------------------------------------------------------------
    # SUMMARY
    # ---------------------------------------------------------------
    header("RESULT")
    print(f"  rule-born data:      {len(stream)//seed_token_bytes}x compression, byte-exact replay  <- claim TRUE")
    print(f"  95%-rule data:       {LENGTH/total_c:.0f}x compression (beats gzip {gz_c/total_c:.1f}x)   <- claim TRUE")
    print(f"  random data:         {total_bytes/LENGTH:.2f}x EXPANSION, chance-level lock-on   <- boundary")
    print(f"  frequency map:       reaches entropy H exactly, never below     <- boundary")
    print()
    print("  CONCLUSION:")
    print("  The scheme works EXACTLY as described - for data born from (or")
    print("  mostly following) the rules. Seeds + rotation + sqrt replay long")
    print("  strings from a few tokens, beating gzip by orders of magnitude.")
    print()
    print("  On truly random data the same scheme expands, because each")
    print("  rule-set names exactly one string and there are vastly fewer")
    print("  few-rule programs than strings. The frequency map is an entropy")
    print("  coder: it reaches the Shannon floor H, which for random bytes")
    print("  is already 8.0 bits/byte.")
    print()
    print("  Compression == how well the rules PREDICT the data. This is the")
    print("  same architecture as zstd/PAQ/LLM compressors: model + residual")
    print("  coder, with the lattice as the model. The winning move is to")
    print("  point it at data with real structure (text, logs, telemetry)")
    print("  and let promotion (Test 6) DISCOVER the rules first.")


if __name__ == "__main__":
    main()
