'use strict';

const {
  buildDoc, saveDoc, H1, H2, H3, P, PR, EQ_NUM, PAGEBREAK,
  BOX, DIAGRAM, BULLET, NUMBERED, OPEN_Q, PREDICTION,
  TextRun, Paragraph, AlignmentType,
} = require('./doc_helpers.js');

const children = [];

// ===================== PART HEADER =====================
children.push(new Paragraph({ spacing: { before: 2400 }, children: [new TextRun('')] }));
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { before: 0, after: 480 },
  children: [new TextRun({ text: 'PART I', size: 36, font: 'Georgia', color: '888888', italics: true })],
}));
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { before: 0, after: 1200 },
  children: [new TextRun({ text: 'THE FOUNDATION', size: 56, bold: true, font: 'Georgia' })],
}));
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { before: 240, after: 0 },
  children: [new TextRun({
    text: 'Chapters 1–2: the π lattice (bisection, π, cells). Part II (Ch 3–7): the 3D complex plane Ψ=(z,ζ) — separate construction, generated by the lattice formula. Parts III–VII put particles, QM, atoms, and cosmology in that plane.',
    size: 22, italics: true, font: 'Georgia', color: '555555',
  })],
}));
children.push(PAGEBREAK());

// ===================== CHAPTER 1 =====================
children.push(H1('Chapter 1: The Lattice of Reality'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { line: 360, after: 0 },
    children: [new TextRun({
      text: 'The universe is a lattice of cells. Each cell has spacetime measure λ_C². Mass fills cells. Energy is mass times that measure. E = mc² is the equation of the lattice.',
      size: 26, italics: true, font: 'Georgia', bold: true,
    })],
  }),
], { shaded: true }));

// ----- 1.1 -----
children.push(H2('1.1  The Universe as a Lattice of Cells'));

children.push(PR(
  'Open with the unification: the universe is a lattice of cells. Each cell carries spacetime measure ',
  { text: 'λ_C²', bold: true },
  ' (width λ_C, depth c·t_cell). Mass is what fills a cell. Energy is fullness times measure: ',
  { text: 'E = mc²', bold: true },
  ' — not a separate conversion miracle, but the cell-area equation of the lattice (**ANCHORED** Einstein; **MODEL** area reading).'
));

children.push(PR(
  'Before wave functions or fields, there is this geometry. Cells are not metaphorical — they are addressable units of reality. The lattice ',
  { text: 'is', italics: true },
  ' the three-dimensional space particles occupy: spring plane z = X + iY, depth ζ, four branches, eight wings — not a diagram drawn on top of some other container (Part II, Ch 3–6). Cartesian (x, y, z) plots are human projections of one chamber at one instant; the native arena is α = (A, b, w, n) on the anchor chain (**MODEL** identification; executable in aethos_complex_plane.py).'
));

children.push(PR(
  'Every particle is a stable bouncing pattern in one cell of that space. Every interaction passes energy between cells. Every measurement samples the lattice state. The photon sea (§1.4) is the continuous medium that fills the same lattice — not a separate box the lattice sits inside.'
));

children.push(BOX([
  new Paragraph({
    spacing: { line: 320, after: 0 },
    children: [new TextRun({
      text: 'Two constructions (see repo ONTOLOGY.md): (1) π lattice — unit-circle bisection below; triangles stack to π and λ_C cells. (2) 3D complex plane — Part II; Ψ=(z,ζ) from the lattice formula on anchor chains. Not the same object; functor between them OPEN.',
      size: 22, italics: true, font: 'Georgia',
    })],
  }),
], { shaded: true }));

children.push(PR(
  'The π lattice does not need a designer or a maintainer. It self-generates by a single iterative rule, applied recursively forever. That rule is the iterative right-triangle tessellation of the unit circle, governed by two geometric identities that will be the foundation of every derivation in this book:'
));

children.push(EQ_NUM('Seed (45° triangle):  A₀² = B₀² = C₀² / 2', '1.1'));
children.push(EQ_NUM('Unit circle:  (1 − A)² + B² = 1', '1.2'));
children.push(EQ_NUM('Recurrence (each step):  B_{k+1} = C_k / 2', '1.2a'));

children.push(PR(
  'Equation (1.1) is the ',
  { text: 'seed halving identity', bold: true },
  ' for the initial 1–1–√2 triangle. It does not repeat as B² = C²/2 at every level once bisection begins; the step rule is (1.2a).'
));

children.push(PR(
  'Equation (1.2) is the ',
  { text: 'unit circle rule', bold: true },
  '. Every lattice point lies on the unit circle. The Pythagorean identity is preserved at every iteration. This is what conserves energy across the lattice.'
));

children.push(PR(
  'Everything that follows in this book — every particle, every force, every quantum phenomenon, every cosmological fact — is a consequence of these rules applied to inner photons bouncing through lattice cells. Chapter 2 aligns book labels with the executable π engine in the companion codebase.'
));

// ----- 1.2 -----
children.push(H2('1.2  Cell Dimensions'));

children.push(P('Each lattice cell has four characteristic quantities. Distinguish the '));
children.push(PR(
  { text: 'cell', bold: true },
  ' (address width) from the ',
  { text: 'coin cavity', bold: true },
  ' (electron bounce span, Chapter 8):'
));

children.push(...DIAGRAM([
  '',
  '                    t_cell (one crossing)',
  '               ┌────────────────────┐',
  '               │                    │',
  '               │                    │   λ_C  (cell width)',
  '               │     ONE CELL       │   = full Compton',
  '               │                    │',
  '               │                    │',
  '               └────────────────────┘',
  '               coin cavity: L = λ_C/2',
  '',
  '        Spacetime measure  A_cell = λ_C × (c × t_cell) = λ_C²',
  '',
], 'Figure 1.1: Lattice cell (width λ_C) and coin half-width L = λ_C/2 (C1 geometry).'));

children.push(BULLET('Cell width: λ_C = h / (m_e c) ≈ 2.43 × 10⁻¹² m (full Compton wavelength).'));
children.push(BULLET('Coin half-width (C1): L = λ_C/2 = h / (2 m_e c).'));
children.push(BULLET('Reduced Compton (QM texts): ƛ_C = ħ / (m_e c) = λ_C / (2π).'));
children.push(BULLET('Cell crossing time: t_cell = λ_C / c = h / (m_e c²) ≈ 8.1 × 10⁻²¹ s.'));
children.push(BULLET('Full pump period: T_bounce = 4L/c = 2 t_cell ≈ 1.6 × 10⁻²⁰ s.'));
children.push(BULLET('Bounce frequency: f_b = 1/T_bounce = m_e c² / (2h) ≈ 6.2 × 10¹⁹ Hz.'));

children.push(PR('The ratio of cell width to cell crossing time gives the lattice update rate:'));

children.push(EQ_NUM('c = λ_C / t_cell', '1.3'));

children.push(PR(
  'This is the speed of light, but viewed mechanically: the lattice advances one cell-width per cell-crossing. ',
  { text: 'c is invariant for all observers', bold: true },
  ' because λ_C and t_cell are fixed properties of the cell geometry, not of the observer.'
));

// ----- 1.3 -----
children.push(H2('1.3  E = mc² — The Equation of the Lattice'));

children.push(PR(
  'Einstein gave the conversion factor. The lattice gives the ',
  { text: 'geometric reason', bold: true },
  ': c² is not an arbitrary square — it is the spacetime ',
  { text: 'area measure', italics: true },
  ' of one cell. Mass m is how much pattern fills that cell. Energy is mass times cell measure. Same structural logic as the seed identity A₀² = B₀² = C₀²/2: squared hypotenuse quantities are ',
  { text: 'area-like', italics: true },
  ' Pythagorean bookkeeping (seed only for the 45° triangle; ongoing steps use B_{k+1} = C_k/2, not B² = C²/2 at every k).'
));

children.push(H3('1.3a  Derivation from the Inner Photon Pump'));

children.push(PR('For a particle of mass m in one cell (C1 geometry):'));

children.push(EQ_NUM('t_{cell} = λ_C / c = h / (m c²)', '1.4b'));
children.push(EQ_NUM('d_{cross} = c · t_{cell} = λ_C', '1.4c'));
children.push(EQ_NUM('E_{cell} = h / t_{cell} = h c / λ_C = m c²', '1.4d'));

children.push(PR(
  'One cell crossing at speed c covers distance λ_C in time t_cell. The action quantum h per crossing time is the rest-energy budget of one filled cell — **ANCHORED** with λ_C = h/(mc). The trapped inner photon pump (Ch 8) runs at f_b = 1/T_bounce with T_bounce = 2 t_cell, so h f_b = mc²/2 per pump half-period; two crossings per full round-trip restore the full mc² ledger.'
));

children.push(H3('1.3b  Cell Area and E = mc²'));

children.push(EQ_NUM('E = m c²  ⟺  E = m · A_{cell} / t_{cell}² · t_{cell}²', '1.4'));
children.push(EQ_NUM('A_{cell} = λ_C · (c t_{cell}) = λ_C²', '1.4a'));
children.push(EQ_NUM('c² = λ_C² / t_{cell}² = A_{cell} / t_{cell}²', '1.4e'));

children.push(PR(
  'Read c² as (lattice step per crossing time)² — the fixed ratio that converts mass filling a cell into energy stored in that cell. Density × area analogy: ρ = m/λ_C², one cell area λ_C², total pattern mass m, internal excitation mc².'
));

children.push(...DIAGRAM([
  '',
  '   ONE LATTICE CELL (electron scale)',
  '   ┌──────────── λ_C ────────────┐',
  '   │                             │  A_cell = λ_C²',
  '   │   trapped inner photon      │  E = m_e c²',
  '   │   crosses at c in t_cell    │  (one filled cell)',
  '   └─────────────────────────────┘',
  '        c·t_cell = λ_C',
  '',
], 'Figure 1.2: Mass fills cell; energy = mass × cell measure.'));

children.push(H3('1.3c  Same Squared C in π Seed and in Einstein'));

children.push(PR(
  'On the unit circle, chord C and legs A, B obey C² = A² + B². At the seed, A₀² = B₀² = C₀²/2 — each leg carries half the squared-hypotenuse budget. In spacetime, c² plays the analogous role for cell measure; E = mc² says rest energy is mass times that measure. ',
  { text: 'Do not conflate', italics: true },
  ' lattice chord C_k with speed c symbol-for-symbol — they are different objects linked by the same Pythagorean squaring logic (**MODEL** unification narrative).'
));

children.push(H3('1.3d  Momentum Linear, Energy Squared'));

children.push(PR(
  'Energy carries two spatial time dimensions in its units (mass·length²/time²) → natural appearance as c². Momentum is mass·length/time → ',
  { text: 'p = mv', bold: true },
  ' without a square (**ANCHORED**). Lattice reading: momentum is length advanced per lattice tick along an external track; energy is the two-dimensional cell measure filled by the pattern.'
));

children.push(EQ_NUM('E² = (m c²)² + (p c)²', '1.4f'));

children.push(PR(
  'Relativistic dispersion is Pythagoras on the (rest-energy, momentum-energy) plane — parallel to (1−A)² + B² = 1 on the address circle and C² = A² + B² on each triangle step. **ANCHORED** SR; **MODEL** as literal triangle overlay.'
));

children.push(H3('1.3e  Squared Quantities in Physics'));

children.push(BULLET('E = mc² — mass × cell spacetime measure (**ANCHORED** + lattice **MODEL**).'));
children.push(BULLET('E² = (mc²)² + (pc)² — energy–momentum Pythagoras (**ANCHORED**).'));
children.push(BULLET('|ψ|² — detection density in sea (**ANCHORED** Born).'));
children.push(BULLET('(1−A)² + B² = 1 — unit-circle constraint (**DERIVED**).'));
children.push(BULLET('KE = ½mv², I²R, mr² inertia — **MODEL/PARTIAL** area readings (O1-6); not all proven from lattice here.'));

children.push(OPEN_Q(
  'Does every squared quantity in physics reduce to a lattice area?',
  'Strong candidates: c² cell measure, |ψ|², Pythagorean energy–momentum. Universal claim remains **OPEN** (O1-6).'
));

// ----- 1.4 -----
children.push(H2('1.4  The Cosmic Ocean (Photon Sea)'));

children.push(PR(
  'The lattice is the address grid; the ',
  { text: 'sea', bold: true },
  ' is the continuous photon medium that fills and connects it. Space is not an empty box — it is this ocean riding the same lattice geometry. Disturbances in the sea are photon packets (E = hf, **ANCHORED**); localized coin patterns (electrons) are filled cells with mc² internal budget (§1.3). The sea carries intrinsic tension — empirical scale v ≈ 246 GeV (Ch 16). No boundaries, no privileged frame.'
));

children.push(PR(
  'The ocean is what allows the lattice to exist. The lattice is the geometric structure of how disturbances propagate through the sea. Without the sea, there would be no medium for the lattice. Without the lattice, there would be no addressable structure in the sea.'
));

children.push(PR(
  { text: 'Microcausality constraint:', bold: true },
  ' the sea is one connected field, but observables at spacelike separation commute — correlations may be nonlocal; controllable faster-than-light signals are forbidden. Disturbances propagate on the light cone at c.'
));

children.push(...DIAGRAM([
  '',
  '         The Cosmic Ocean (tension scale v ≈ 246 GeV)',
  '  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒',
  '  ▒┌──┬──┬──┬──┬──┬──┬──┬──┬──┬──┬──┬──┬──┬──┬──┬──┐▒',
  '  ▒│  │  │  │  │  │  │  │  │  │  │  │  │  │  │  │  │▒',
  '  ▒├──┼──●──┼──┼──┼──┼──┼──┼──┼──○──┼──┼──┼──┼──┼──┤▒',
  '  ▒│  │  │  │  │  │  │  │  │  │  │  │  │  │  │  │  │▒',
  '  ▒├──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼──┼──┤▒',
  '  ▒│  │  │  │  │  │ ●│  │  │  │  │  │  │  │  │  │  │▒',
  '  ▒└──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┴──┘▒',
  '  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒',
  '',
  '     Cells: lattice addresses    ● = localized pattern (electron)',
  '     Sea: continuous medium      ○ = empty address',
  '',
], 'Figure 1.3: The lattice and the ocean.'));

children.push(H2('1.4a  Free Photons vs Localized Patterns'));

children.push(BULLET('Free photons: no coin, spring, or trapped engine → no internal clock (dτ = 0 along lightlike paths).'));
children.push(BULLET('ψ_S: disturbance amplitude in the sea; |ψ|² is detection density (Born rule).'));
children.push(BULLET('Sea light as vapor: mode quanta with E_λ = h f_λ (spectrum / color / laser lines).'));
children.push(BULLET('Electrons: localized pump patterns in one cell; bounce period T_bounce sets the clock (Chapter 8).'));

children.push(PR('Inside this picture, every familiar physical entity is a pattern in the sea:'));

children.push(BULLET('Electrons: bouncing inner photon in a coin cavity of half-width L — moving in the ℂ × ℝ lattice (Ch 3–6).'));
children.push(BULLET('Protons: fused, more compressed structures (Chapter 9).'));
children.push(BULLET('Photons: traveling disturbances without internal structure — pure motion at c.'));
children.push(BULLET('Atoms: nested resonances (Chapter 15).'));
children.push(BULLET('Gravity: gradient flow in the sea toward mass concentrations (Chapter 19).'));
children.push(BULLET('Dark matter: lattice structures without inner photons (Chapter 17).'));
children.push(BULLET('Dark energy: escaped inner photons — negative-pressure component (Chapter 17).'));

// ----- 1.5 -----
children.push(H2('1.5  Particles as Lattice Structures'));

children.push(PR(
  'What is a particle? Not a tiny billiard ball. Not a point with mass. A ',
  { text: 'particle is a stable bouncing pattern occupying one lattice cell', bold: true },
  '. The cell width λ_C sets the address scale. The bouncing pattern sets identity. The bounce frequency sets mass.'
));

children.push(PR('An electron is a trapped inner photon bouncing across a coin of half-width L. The bounce frequency is:'));

children.push(EQ_NUM('f_b = 1 / T_bounce = m_e c² / (2h)', '1.5'));

children.push(PR(
  'For an electron: f_b ≈ 6.2 × 10¹⁹ Hz. This is the pump rate — the zitterbewegung frequency in conventional language. ',
  { text: 'Do not confuse', italics: true },
  ' f_b with 1/t_cell; the full round-trip pump takes T_bounce = 2 t_cell.'
));

children.push(PR(
  'More massive particles occupy smaller cells. The inner photon traverses less distance per cycle, so the frequency rises. Higher frequency, higher energy per cycle, higher mass. Chapter 12 develops the mass hierarchy through sea tension.'
));

// ----- 1.6 -----
children.push(H2('1.6  The Pi Formula: Foundation of the Lattice'));

children.push(PR(
  'The lattice is generated by iterative right-triangle bisection on the unit circle. Begin at (1, 0). Each step halves the previous hypotenuse as a new leg and projects a new point onto the circle. Continue indefinitely.'
));

children.push(...DIAGRAM([
  '',
  '         iteration 0          iteration 1          iteration 2',
  '',
  '            ●                    ●                    ●',
  '                               ╱│                   ╱│╲',
  '                              ╱ │                  ╱ │ ╲',
  '                             ╱  │                 ●  │  ●',
  '                            ╱   │ B              ╱│  │ ╱│',
  '                           ╱    │               ╱ │  │╱ │',
  '                          A─────│              ●  │  │  ●',
  '',
  '         1 point               3 points              5 points',
  '',
  '    Step rule: B_{k+1} = C_k/2 ;  (1−A)² + B² = 1',
  '',
], 'Figure 1.4: Three iterations of the π lattice.'));

children.push(PR('At each iteration k (code labels: see Chapter 2):'));

children.push(EQ_NUM('B_{k+1} = C_k / 2', '1.6'));
children.push(EQ_NUM('A_{k+1} = 1 − √(1 − B_{k+1}²)', '1.7'));
children.push(EQ_NUM('C_{k+1} = √(A_{k+1}² + B_{k+1}²)', '1.8'));

children.push(PR(
  'Starting from B_0 = 0 on the x-axis, the legs produce nested radicals — √2/2, √(2−√2)/2, … — from arithmetic alone. No imported π, sin, or cos.'
));

children.push(PR('The inscribed polygon at level k has N_k = 4·2^k edges of chord length C_k. Half the perimeter approaches π:'));

children.push(EQ_NUM('P_k = N_k · C_k / 2', '1.9'));
children.push(EQ_NUM('π = lim_{k→∞} 2^{k+1} · C_k', '1.10'));

children.push(PR(
  'This is a constructive definition of π: a limit of discrete triangle subdivisions. Each iteration adds exactness; the limit ',
  { text: 'is', italics: true },
  ' π. Verified against the executable recurrence in the companion π engine.'
));

children.push(OPEN_Q(
  'Is π fundamental to nature, or derived from a more basic structure?',
  'The lattice answer: π is derived — the smooth limit of right-triangle bisection. Where π appears in physics, it is the continuum envelope of discrete lattice refinement.'
));

// ----- 1.7 -----
children.push(H2('1.7  Why Particles Do Not Calculate'));

children.push(PR(
  'This is the deepest claim of the book: particles do not know mathematics. They do not evaluate cos, sin, π, or differential equations. They ',
  { text: 'bounce', bold: true },
  ' — one right-triangle step at a time, +B or −B. Equations are human compression of what the geometry already enforces.'
));

children.push(H3('1.7a  Triangles, Not Trigonometry'));

children.push(PR(
  'At each iteration the inner photon moves from one lattice vertex to the next. The step rule B_{k+1} = C_k/2 halves the previous hypotenuse as a new leg; the constraint (1−A)²+B²=1 projects the landing point back onto the unit circle. The photon does not compute these identities — they are the ',
  { text: 'only', italics: true },
  ' way the lattice can subdivide. cos θ and sin θ are continuum limits over many vertices (Chapter 2.10.5) — shadows on the unit circle, not separate from the spring-plane space particles traverse.'
));

children.push(...DIAGRAM([
  '',
  '   PARTICLE VIEW              HUMAN VIEW',
  '   ─────────────              ──────────',
  '   bounce A → B               write ψ(x,t)',
  '   pick +B or −B              write superposition',
  '   halve chord C              write wave equation',
  '   stay on x²+y²=1            write conservation laws',
  '',
  '   Same motion. Two languages.',
  '',
], 'Figure 1.5: Mechanism vs description.'));

children.push(H3('1.7b  Two Branches Every Step'));

children.push(PR(
  'Given position (1−A_k, y_k), the next depth offers exactly two y-values: +B_{k+1} and −B_{k+1} at x = 1−A_{k+1}. Orientation (coin state, spring axis) determines which branch the bounce accesses — geometric gating, not informational messaging. Spin up/down, electron/positron, particle/antiparticle read as ±B preference at each gate — **MODEL** (CP asymmetry why matter dominates: **OPEN**).'
));

children.push(H3('1.7c  2^k Positions and Partner Search'));

children.push(PR(
  'Depth k carries 2^k binary branch words — effectively dense on the circle only for large k. Every electron seeks compatible partners in the sea (entanglement as shared address in the same lattice, Ch 12). In vacuum: few scatterers, Γ_break low, a rare lock can persist. In dense matter or bright environments: constant partner exchange, rapid τ_E turnover — **MODEL** (pressure-controlled Bell tests **ANCHORED**). Bound atoms constrain k to resonance shells — stronger, shorter-range pairing patterns.'
));

children.push(H3('1.7d  Conservation Without Postulates'));

children.push(PR(
  'Single particle on the circle: (1−A_k)²+B_k²=1 always. Entangled mirror pair at (1−A_k, ±B_k): each radius 1, combined squared norm 2 — geometric bookkeeping, not an added conservation law. When Alice\'s measurement pins +B_k, Bob\'s −B_k is fixed by the shared x-coordinate and mirror rule — Bell correlation as kinematic consistency (**ANCHORED** E(α,β)=−cos(α−β); lattice closure **PARTIAL** C5).'
));

children.push(EQ_NUM('|A|² + |B|² = 1  \\quad\\text{(one particle)}', '1.11'));
children.push(EQ_NUM('2\\bigl((1-A_k)^2 + B_k^2\\bigr) = 2  \\quad\\text{(mirror pair)}', '1.12'));

children.push(H3('1.7e  Why c Is Fixed'));

children.push(PR(
  'c = λ_C/t_cell: one full cell width per crossing time. The lattice step and iteration clock do not vary with observer motion; what splits is the budget between internal bounce (proper time) and external drift:'
));

children.push(EQ_NUM('v_{space}^2 + v_{time}^2 = c^2', '1.13'));

children.push(PR(
  'Photons spend 100% on external steps (no trapped pump). Electrons at rest spend 100% on internal bounce. Skipping an iteration (k→k+2) is geometrically illegal — no lattice shortcuts — **MODEL** reading of light-speed limit. Cannot exceed c without leaving the address tree.'
));

children.push(H3('1.7f  Probability Is Often Our Ignorance'));

children.push(PR(
  'Each bounce lands on a ',
  { text: 'definite', italics: true },
  ' vertex. Apparent randomness enters when we do not track full bounce ledger, partner depth k_env, or polarizer axis history. cos²(θ/2) remains the measured envelope (Malus, **ANCHORED**); underneath, discrete branch counts — **PARTIAL** (O1-1, O12-1). This is not a return to classical hidden tags unless superposition itself is denied; depths can stay unresolved until a polarizer samples a branch.'
));

children.push(NUMBERED('Reality is discrete at cell scale; continuity is a many-bounce average.'));
children.push(NUMBERED('Mathematics describes; geometry executes.'));
children.push(NUMBERED('No zero-width instant — only finite frames (Section 12 / Ch 2).'));
children.push(NUMBERED('Time = pump tick count; arrow from irreversible forward pumping (Ch 18).'));

children.push(PREDICTION(
  'Below t_cell ≈ 10⁻²⁰ s: discrete steps, not smooth continuity. Fresh-electron statistics within one t_cell may deviate from smooth cos²(θ/2) — **TEST**.'
));

// ----- 1.8 -----
children.push(H2('1.8  What This Theory Explains'));

children.push(PR('From the lattice rules and the sea ontology above, this book derives — each in its own chapter:'));

children.push(BULLET('π lattice — bisection, ±B, S_k→π, Compton cells (Chapters 1–2).'));
children.push(BULLET('3D complex plane — Ψ=(z,ζ), lattice formula, 32 chambers, SequenceKind (Chapters 3–7).'));
children.push(BULLET('Electron, proton, neutron — masses, spins, coin pump (Chapters 8–10).'));
children.push(BULLET('Measurement — Born/Malus on spring z-plane (Chapter 11).'));
children.push(BULLET('Entanglement and Bell — ±B mirrors and swap meets (Chapter 12).'));
children.push(BULLET('Tunneling — exponential suppression (Chapter 13).'));
children.push(BULLET('Double slit — wake interference (Chapter 14).'));
children.push(BULLET('Atom — Bohr radius, shells, periodic table (Chapter 15).'));
children.push(BULLET('Higgs — sea tension v = 246 GeV (Chapter 16).'));
children.push(BULLET('Dark matter and dark energy (Chapter 17).'));
children.push(BULLET('Time, c, relativity — lattice iteration (Chapter 18).'));
children.push(BULLET('Gravity — cosmic clock synchronizer (Chapter 19).'));
children.push(BULLET('Grand synthesis — right triangle breaking down forever (Chapter 20).'));

children.push(PR(
  'The theory does not replace standard physics. It provides the ',
  { text: 'geometric mechanism', bold: true },
  ' underneath tested equations. The formulas stay the same; the interpretation becomes mechanical.'
));

// ----- 1.9 -----
children.push(H2('1.9  Master Equations of Chapter 1'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
    children: [new TextRun({ text: 'FOUNDATIONAL EQUATIONS', bold: true, size: 22, font: 'Georgia' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'Seed: A₀² = B₀² = C₀²/2  (1.1)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 120 },
    children: [new TextRun({ text: '(1−A)² + B² = 1  (1.2)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'c = λ_C / t_cell  (1.3)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'E = m c² ;  A_cell = λ_C² ;  E² = (mc²)²+(pc)²  (1.4–1.4f)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'E_cell = h/t_cell = mc²  (1.4d)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'f_b = m_e c² / (2h)  (1.5)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'B_{k+1} = C_k/2  (1.6)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 60 },
    children: [new TextRun({ text: 'π = lim 2^{k+1} C_k  (1.10)', size: 22, font: 'Cambria Math' })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER,
    spacing: { after: 0 },
    children: [new TextRun({ text: 'C1: L = λ_C/2', size: 20, font: 'Georgia', italics: true })],
  }),
], { shaded: true }));

children.push(PAGEBREAK());

(async () => {
  const doc = buildDoc('1', 'Chapter 1 — The Lattice of Reality', children);
  await saveDoc(doc, 'book/output/01_The_Lattice_of_Reality.docx');
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
