'use strict';

const {
  buildDoc, saveDoc, H1, H2, H3, P, PR, EQ_NUM, PAGEBREAK, NUMBERED,
  BOX, DIAGRAM, BULLET, OPEN_Q, PREDICTION,
  TextRun, Paragraph, AlignmentType,
} = require('./doc_helpers.js');

const children = [];

// ===================== PART II HEADER =====================
children.push(new Paragraph({ spacing: { before: 2400 }, children: [new TextRun('')] }));
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { before: 0, after: 480 },
  children: [new TextRun({ text: 'PART II', size: 36, font: 'Georgia', color: '888888', italics: true })],
}));
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { before: 0, after: 1200 },
  children: [new TextRun({ text: 'THE 3D COMPLEX PLANE', size: 56, bold: true, font: 'Georgia' })],
}));
children.push(new Paragraph({
  alignment: AlignmentType.CENTER,
  spacing: { before: 240, after: 0 },
  children: [new TextRun({
    text: 'Chapters 3–7: the 3D complex plane Ψ = (z, ζ) ∈ ℂ × ℝ — the arena, generated by the lattice formula on anchor chains. Not the π lattice (Ch 1–2). Primes name one species; unbounded n/k/depth is extension. 32 chambers, origin-tree nesting, Hilbert completion.',
    size: 22, italics: true, font: 'Georgia', color: '555555',
  })],
}));
children.push(PAGEBREAK());

// =====================================================================
// CHAPTER 3
// =====================================================================
children.push(H1('Chapter 3: State Space — Ψ = (z, ζ)'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { line: 360, after: 0 },
    children: [new TextRun({
      text: 'This is the 3D complex plane — not a "prime lattice" or "infinity lattice." Those were labels for the formula and its extension; the thing itself is Ψ = (z, ζ). The π lattice (Ch 1–2) is a separate construction (unit-circle bisection). The lattice formula on anchor chains generates this plane.',
      size: 22, italics: true, font: 'Georgia',
    })],
  }),
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { before: 240, line: 360, after: 0 },
    children: [new TextRun({
      text: 'Part II is a mathematical construction. Parts III–VI are physical readings. The advance is the lattice formula and its 32-chamber closure — not particle metaphor alone.',
      size: 22, bold: true, font: 'Georgia',
    })],
  }),
]));

children.push(H2('3.1  Construction, Not Coordinate Chart'));

children.push(PR(
  'Two ways to read the same formulas. This book takes the ',
  { text: 'construction', bold: true },
  ' reading as primary:'
));

children.push(...DIAGRAM([
  '',
  '   COORDINATE CHART (secondary):   Fix C x R.  Map labels -> (z, zeta).',
  '   CONSTRUCTION (primary):         Primitive rules -> trajectories -> readout (z, zeta).',
  '',
  '   PRIMITIVE:   rail n, chain A, segment s, branch b, wing w, meet quotient',
  '   READOUT:     z = X + iY,   zeta = Z',
  '   OBJECT:      3D complex plane = trajectory space + readout (**MODEL** physics)',
  '',
], 'Figure 3.0: Primitive / readout / object.'));

children.push(BULLET('**PRIMITIVE (DERIVED):** transgressor n ∈ ℕ; anchor chain A = (a₁,…,a_k); segment FSM; four branch algebras VA1–VA4; eight wing operators; swap_meet / triple_equalization glue banks.'));
children.push(BULLET('**READOUT (DERIVED):** canon_on_chain(b,A,n) → (X,Y,Z); wing w → (X_w,Y_w,Z_w); then z = X_w + iY_w, ζ = Z_w.'));
children.push(BULLET('**OBJECT (MODEL):** the 3D complex plane is this rule-driven trajectory space equipped with (z,ζ) — not a blank graph the formula is drawn on.'));
children.push(BULLET('**PROVEN:** wing operators **define** i and conjugation on the spring plane before readout — see §3.1b (`aethos_spring_complex.py`).'));
children.push(BULLET('**PARTIAL:** π lattice ↔ plane functor at layer 0 and demo maps — see §3.4 (`aethos_pi_bridge.py`); full label map **OPEN**.'));

children.push(H2('3.1b  Wing Operators Define ℂ (Not Only Read i)'));

children.push(PR(
  'The readout z = X + iY is a ',
  { text: 'camera', italics: true },
  '. The imaginary unit is already in the primitive operators. Work in real pairs (X, Y) only:'
));

children.push(EQ_NUM('S(X,Y) = (Y,X),\\quad R_x(X,Y) = (-X,Y)', '3.0a'));
children.push(EQ_NUM('i_{\\mathrm{act}} = R_x \\circ S:\\quad (X,Y) \\mapsto (-Y,\\, X)', '3.0b'));
children.push(EQ_NUM('\\mathrm{conj}_{\\mathrm{act}}(X,Y) = (X,-Y)\\quad\\text{(equals } -R_x \\text{ on } z=X+iY\\text{)}', '3.0c'));

children.push(PR('On readout z = X + iY:'));
children.push(EQ_NUM('i_{\\mathrm{act}}(X,Y) \\leftrightarrow i\\cdot z = -Y + iX', '3.0d'));
children.push(EQ_NUM('i_{\\mathrm{act}} \\circ i_{\\mathrm{act}} \\leftrightarrow -z', '3.0e'));

children.push(...DIAGRAM([
  '',
  '   Spring (no imported i):     i_act(1, 0) = (0, 1)',
  '   Readout check:              (0, 1)  ->  0 + i*1  =  i',
  '   Matches:                    reflect_real(swap_corridor(1+0j)) == 1j',
  '',
  '   Code: aethos_spring_complex.py   Tests: tests/test_spring_complex.py',
  '',
], 'Figure 3.0b: i from operators, not from readout import.'));

children.push(BULLET('**PROVEN:** Klein four {id, R_x, S, R_x∘S} on z; i_act = R_x∘S (**DERIVED** tests).'));
children.push(BULLET('**PARTIAL:** full ℂ field multiplication on every VA1 trajectory (sampled; not closed-form all n).'));

children.push(H2('3.2  The Formula Pipeline (Concrete)'));

children.push(PR('Six executable steps — `aethos_sequences.canon_on_chain` + `aethos_complex_plane.wing_transform`:'));

children.push(NUMBERED('**Chain:** A = make_chain(kind, k) — strictly increasing anchors (PRIMES, EVENS, CUSTOM, …).'));
children.push(NUMBERED('**Segment:** s = segment_index(A, n) — which regime n occupies (0 … k).'));
children.push(NUMBERED('**Depth:** ζ = Z(A,n,s) — third axis; interior lock when 0 < s < k and k > 2.'));
children.push(NUMBERED('**Branch:** (X,Y,Z) = canon_on_chain(b, A, n) — VA1–VA4 algebra on same segments.'));
children.push(NUMBERED('**Wing:** (X_w,Y_w,Z_w) = apply_vector(X,Y,Z, wing_w) — Klein flips / Y-over swap.'));
children.push(NUMBERED('**Plane:** Ψ = (z, ζ) with z = X_w + iY_w, ζ = Z_w ∈ ℂ × ℝ.'));

children.push(EQ_NUM('s = \\mathrm{segment\\_index}(A,n),\\quad 0 \\le s \\le k', '3.1'));

children.push(EQ_NUM('\\zeta = \\begin{cases} \\sum A + n & k \\le 2 \\text{ or } s \\in \\{0,k\\} \\\\ \\sum A & 0 < s < k \\end{cases}', '3.2'));

children.push(PR('VA1 branch (same segment breaks for VA2–VA4; different (X,Y) algebra):'));

children.push(EQ_NUM('\\text{VA1:}\\quad s{=}0 \\Rightarrow (a_1{+}a_k,\\, a_1,\\, \\zeta);\\quad 0{<}s{<}k \\Rightarrow (a_k{+}n,\\, n,\\, \\zeta);\\quad s{=}k \\Rightarrow (a_k{+}n,\\, a_k,\\, \\zeta)', '3.3'));

children.push(EQ_NUM('\\Psi = (z,\\zeta),\\quad z = X_w + iY_w,\\quad \\zeta = Z_w', '3.4'));
children.push(EQ_NUM('\\alpha = (A, b, w, n)', '3.5'));

children.push(H2('3.3  Worked Example (PRIMES, k = 5, n = 10)'));

children.push(PR('A = (3, 5, 7, 11, 13), ΣA = 39. Since 7 ≤ 10 < 11, segment s = 3 (interior) ⇒ ζ = 39 (plateau). Wing 1:'));

children.push(...DIAGRAM([
  '',
  '   Branch    (X, Y, Z)      z = X+iY       |z|^2',
  '   ─────────────────────────────────────────────',
  '   VA1       (23, 10, 39)   23+10i          629',
  '   VA2       (29,-10, 39)   29-10i          941',
  '   VA3       (16, -3, 39)   16-3i           265',
  '   VA4       (36,  3, 39)   36+3i          1305',
  '',
  '   Same n, same zeta — four distinct z. 32 chambers = 4 x 8 wings.',
  '',
], 'Table 3.1: canon_on_chain + wing_transform (reproducible in Python).'));

children.push(...DIAGRAM([
  '',
  '   from aethos_sequences import make_chain, SequenceKind',
  '   from aethos_complex_plane import wing_transform',
  '   from aethos_lattice import BranchKind',
  '',
  '   A = make_chain(SequenceKind.PRIMES, 5)',
  '   psi = wing_transform(BranchKind.VA1, A, n=10, wing=1)',
  '   # psi.z == 23+10j, psi.zeta == 39',
  '',
], 'Listing 3.1: One line to the plane.'));

children.push(H2('3.4  π Lattice vs 3D Complex Plane (Functor Status)'));

children.push(BULLET('**π lattice (Ch 1–2):** (1−A_k, ±B_k), S_k→π, λ_C cells — **separate construction**.'));
children.push(BULLET('**3D complex plane (here):** Ψ from Steps 3.2 — anchor FSM, not unit-circle bisection.'));
children.push(BULLET('**PROVEN bridges:** layer 0 diagonal z₀=n+ni has angle π/4 = pi vertex (k=1,j=1); pi k=0 unit point (0,1) = i_act(1,0).'));
children.push(BULLET('**PARTIAL maps** (`aethos_pi_bridge.py`): depth k ↦ n=2^k; ±B bit tail ↦ wing mask; embed_pi_vertex_layer0 matches angles on tested (k,j).'));
children.push(BULLET('**OPEN:** canon_on_chain(prime A, n) = π walker at shared label for all k and chains.'));

children.push(...DIAGRAM([
  '',
  '   pi/constructive_pi          aethos_pi_bridge           3D complex plane',
  '   ─────────────────────────────────────────────────────────────────────',
  '   point_on_circle(k,j)   ->   angle / scale match   ->   z0 = n(1+i) ray',
  '   primitive_root k=0     ->   i_act(1,0)=(0,1)      ->   wing readout i',
  '   bisection depth k      ->   n = 2^k (demo)        ->   transgressor rail',
  '   ±B branch bits         ->   wing mask 0..7        ->   Klein chamber',
  '',
], 'Figure 3.2: Partial functor — proven at layer 0 and i; full label map OPEN.'));

children.push(H2('3.5  Native Address and Camera View'));

children.push(BULLET('A — countable anchor chain (crossing history).'));
children.push(BULLET('b — branch VA1..VA4 (four spring algebras at one node).'));
children.push(BULLET('w — wing 1..8 (Klein corridors).'));
children.push(BULLET('n — transgressor on the 1D rail.'));

children.push(PR(
  'Plot (Re z, Im z, ζ) in ℝ³ is a ',
  { text: 'camera', italics: true },
  ' on one (b,w) at one n. The object includes all branches, wings, path history, and meet quotients — segment FSM **DERIVED** (test_complex_plane.py); physical arena **MODEL** (Ch 8).'
));

children.push(H2('3.5b  Terminology — Imaginary Complex Number (ICN)'));

children.push(PR(
  'AETHOS name (**MODEL**, not standard math): an ',
  { text: 'imaginary complex number', bold: true },
  ' (ICN) is a ',
  { text: 'prime composite', italics: true },
  ' C = p₁·p₂·… whose unique factorization normalizes back to the imaginary-axis prime alphabet, then lands on the plane as readout Ψ = (z, ζ).'
));

children.push(BULLET('**ICN** — composite address on the promotion/encoding axis (`aethos_phrase_composite`, `aethos_intersection_nodes`). **MODEL**'));
children.push(BULLET('**Complex readout** — z = X + iY after wing transform; 2-way spring meet. **DERIVED**'));
children.push(BULLET('**3-way meet** — Ψ = (z, ζ) or triple equalization / triple composite; full intersection node. **DERIVED**'));
children.push(BULLET('**Normalize down** — factor C → sorted prime chain A → `canon_on_chain` → (z, ζ); non-primes exist only as products of primes. **PROVEN** (FTA) + **DERIVED** (code)'));
children.push(BULLET('**Not the same as** textbook “complex number” a + bi — ICN names composite addresses; z names the camera readout.'));

children.push(...DIAGRAM([
  '',
  '   PROMOTE UP (frequency / meet)          NORMALIZE DOWN (FTA)',
  '   letters -> pool primes -> ICN C        C -> factors -> chain A -> Psi=(z,zeta)',
  '',
  '   32 lattices = 1 vector x (4 branch fans x 8 wing labels), not 32 new ICNs.',
  '',
], 'Glossary 3.5b: ICN vs complex readout vs meet.'));

children.push(H2('3.5c  Glossary — Vector Hierarchy (Patent Language)'));

children.push(PR(
  'AETHOS uses ',
  { text: 'vector', bold: true },
  ' not ',
  { text: 'axis', italics: true },
  ': vectors move; axes are static chart lines. Three **MODEL** terms (disambiguate from textbook math in every formal doc):'
));

children.push(BULLET('**Imaginary vector** — phase engine: spring (X,Y), wing operators, branch b (main stick, 4 sub-quadrant fans). Turns the gear.'));
children.push(BULLET('**Complex vector** — 2-way meet path: swap-meet witness bank(a)@n=p ↔ bank(p)@n=a; trajectory with z = X+iY locked along the rail. Drives the path.'));
children.push(BULLET('**Complex number** — 3-way meet destination: Ψ = (z, ζ) at triple equalization (e.g. (3,5)@7, (3,7)@5, (5,7)@3 → one node). Locks the final coordinate — not a+bi alone.'));
children.push(BULLET('**ICN** (§3.5b) — prime composite on the encoding layer; normalize down by FTA. Separate from the three vectors above.'));

children.push(...DIAGRAM([
  '',
  '   TRANSMISSION (32 chambers = 1 linkage)',
  '   Main stick (b)  ->  4 branch gears     [imaginary vector phase]',
  '   Thumb stick (w) ->  8 wing octants      [Klein x zeta]',
  '   Road A + mile n ->  chain + transgressor',
  '',
  '   IMAGINARY VECTOR  --turns-->  COMPLEX VECTOR  --locks-->  COMPLEX NUMBER',
  '   (phase/branch)                 (2-way path)                  (3-way Psi)',
  '',
], 'Figure 3.3: Vector hierarchy + joystick transmission.'));

children.push(PR('Repo canonical glossary: `ONTOLOGY.md` §B.5–B.6. Code: `aethos_complex_plane.py` module docstring.'));

children.push(H2('3.6  Layer 0 — Imaginary Start'));

children.push(PR('Empty chain |A| = 0 — all four branches agree at the origin rail:'));

children.push(EQ_NUM('z_0(n) = n + n i = n(1 + i),\\quad \\zeta_0(n) = n', '3.6'));

children.push(PR(
  'Every branch starts on the diagonal of the spring plane — the imaginary-axis seed. No trig input: coordinates come from the segment rules only (**DERIVED** in code).'
));

children.push(H2('3.7  Layer 1 — Single Anchor'));

children.push(PR(
  'One anchor a in the chain. VA1 (primary branch): before the anchor regime, Y walks on the imaginary axis; after n ≥ a, Y ',
  { text: 'locks', bold: true },
  ' at a (velocity boundary). Depth ζ = a + n. Displacement at the crossing n = a: dz = a + ai. This is the first ',
  { text: 'trigger node', bold: true },
  ' — spring bounce in the electron picture (Ch 8 preview).'
));

children.push(...DIAGRAM([
  '',
  '   SPRING PLANE z = X + iY          DEPTH ζ',
  '        Im (Y)                          │',
  '         │    z = n+ni (layer 0)        │  ζ grows with',
  '         │         ╲                    │  anchor sum + n',
  '         └────────── Re (X)              ▼',
  '',
], 'Figure 3.1: ℂ spring plane + ℝ depth axis (not a flat complex plane alone).'));

children.push(H2('3.8  Layer k — Segment FSM'));

children.push(PR(
  'Chain A = (a₁, …, a_k). Transgressor n falls in segment s ∈ {0,…,k}: before a₁, between anchors, or after a_k. VA1 formulas (documentation closed form in derive_va1_closed_form):'
));

children.push(BULLET('s = 0: (a₁ + a_k, a₁, ζ) — approach first anchor.'));
children.push(BULLET('0 < s < k: (a_k + n, n, ζ) — interior corridor.'));
children.push(BULLET('s = k: (a_k + n, a_k, ζ) — post-final-anchor regime.'));

children.push(PR(
  'Depth ζ: for k ≤ 2 or boundary segments, ζ = sum(A) + n; for interior 0 < s < k with lock_interior, ζ = sum(A) only — ',
  { text: 'bulk lock', bold: true },
  ' while X,Y still move. **MODEL** reading: interior = photon-sea bulk between boundary triggers (§5.3).'
));

children.push(H2('3.9  Connection to Chapters 1–2'));

children.push(PR(
  'Ch 1 cells (λ_C) set the floor scale from the ',
  { text: 'π lattice', italics: true },
  '. Ch 3–7 name the ',
  { text: '3D complex plane', bold: true },
  ' where the inner photon bounces: spring coordinates (X, Y, ζ) between triggers. Same physics story; partial functor at layer 0 and i (**PROVEN** §3.4); full label map **OPEN**.'
));

children.push(BULLET('π addresses (1−A, ±B): high-k limit of refined spring plane — same bisection logic, same space.'));
children.push(BULLET('E = mc² cell λ_C²: z spans coin face; ζ stacks anchor composition along depth.'));
children.push(BULLET('|z|²: spring tension² → Born envelope (Ch 4 §4.4; O1-1 **PARTIAL**).'));
children.push(BULLET('Particles do not calculate: canon_on_chain is FSM evaluation, not Schrödinger (**MODEL**).'));

children.push(H2('3.10  Countable Anchor Sets — Species on the Plane'));

children.push(PR(
  'The same VA1–VA4 formulas and 32 wings apply to ',
  { text: 'any', bold: true },
  ' strictly increasing countable chain A = (a₁, a₂, …). The ',
  { text: 'set', italics: true },
  ' (species) is not decoration — it defines segment breaks, plateau width, and meet geometry. Implemented species (aethos_sequences.SequenceKind):'
));

children.push(BULLET('PRIMES — odd primes 3, 5, 7, 11, … (2 skipped).'));
children.push(BULLET('EVENS — 2, 4, 6, 8, …'));
children.push(BULLET('POWERS_OF_2 — 2, 4, 8, 16, …'));
children.push(BULLET('FIBONACCI, SQUARES, TRIPLES, SQRT_SCALED — same engine, different collision schedule.'));
children.push(BULLET('CUSTOM — any normalize_chain() input; must be strictly increasing.'));

children.push(EQ_NUM('A = \\mathrm{make\\_chain}(\\mathrm{kind}, k) \\quad\\Rightarrow\\quad |A| = k \\text{ anchors; extend } k \\to \\infty \\text{ countably}', '3.7'));

children.push(PR(
  'At fixed n, primes vs evens vs powers_of_2 yield ',
  { text: 'different', bold: true },
  ' (X,Y,ζ) — **PROVEN** (test_different_species_differ_at_same_n). Physics: species chooses which anchor template on the **3D complex plane**, not a tag pasted on afterward (**MODEL**).'
));

children.push(OPEN_Q(
  'Prove every π-tree leaf embeds in some (A, b, w, n) without loss?',
  'PARTIAL — layer 0, unit i, dyadic vertices, demo depth→n and bits→wing (`aethos_pi_bridge.py`); full chain label map OPEN.'
));

children.push(PAGEBREAK());

// =====================================================================
// CHAPTER 4
// =====================================================================
children.push(H1('Chapter 4: Thirty-Two Chambers — Branches and Wings'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { line: 360, after: 0 },
    children: [new TextRun({
      text: 'Four branches × eight wings = 32 sub-chambers. Branches re-canonicalize (X,Y,ζ); wings apply Klein-4 on z and ζ reflection. This is the mechanical root of four-state and spinor-720° bookkeeping.',
      size: 22, italics: true, font: 'Georgia',
    })],
  }),
]));

children.push(H2('4.1  Four Branches — Four Spring Algebras'));

children.push(PR(
  'At fixed (A, w, n), branches VA1..VA4 yield ',
  { text: 'four distinct', bold: true },
  ' complex values z — tests confirm four different z, often one shared ζ. These are not cosmetic labels: each branch runs a different (X,Y) algebra on the same segment FSM (aethos_recursive.CANON).'
));

children.push(PR(
  '**Book link (distinct layers):** coin states WH/WS/BH/BS (Ch 8) = membrane side × spring tension. Branch fan VA1–VA4 = formula fan on the spring plane at one trigger. Both give ',
  { text: 'four', italics: true },
  ' outcomes; do not identify them term-for-term without a proven map (**PARTIAL**).'
));

children.push(H2('4.2  Eight Wings — Klein Corridors'));

children.push(PR(
  'Wings 1–4 (VA family): optional flip_x, flip_z on (X, Y, ζ). Wings 5–8 (VB family): swap (Y, X, ζ) then flips — Y–Z corridor lead. Spring operators on z (order-2 generators):'
));

children.push(EQ_NUM('R_x(z) = -\\mathrm{Re}(z) + i\\,\\mathrm{Im}(z)', '4.1'));
children.push(EQ_NUM('S(z) = \\mathrm{Im}(z) + i\\,\\mathrm{Re}(z)', '4.2'));
children.push(EQ_NUM('J: (z, \\zeta) \\mapsto (z, -\\zeta)', '4.3'));

children.push(PR(
  'Klein closure on z: {z₀, R_x z₀, S z₀, R_x S z₀}. With ζ hemisphere: 4 × 2 = 8 wings. Full chamber count: 4 branches × 8 wings = ',
  { text: '32', bold: true },
  ' (lattice_id = 1 + b×8 + (w−1)).'
));

children.push(...DIAGRAM([
  '',
  '   ONE NODE (A, n)  —  4 branches × 8 wings = 32 chambers',
  '',
  '   branch b=0..3  ──┬── wing w=1..8  ──►  Ψ_{b,w} = (z, ζ)',
  '                    │',
  '                    └── same (X,Y,ζ) possible; distinct (b,w) = distinct state label',
  '',
], 'Figure 4.1: Branch fan × wing mask.'));

children.push(H2('4.3  Rotation Sweep'));

children.push(PR(
  'Flat index k ∈ {0,…,31} walks all chambers: branch-major or wing-major order (aethos_complex_rotation.py). Branch step is ',
  { text: 're-canonicalize', italics: true },
  ', not a fixed e^{iπ/2} multiply of one z — important honesty tag: Arg(z) step is not uniform across branches (**DERIVED** from code, not elementary rotation).'
));

children.push(H2('4.4  Spring Tension and |z|²'));

children.push(PR(
  'Section 2 spring picture: elongation u ~ Re(ψ); tension T ∝ |ψ|². On the complex plane, |z|² is detection density — Malus/Born limit (Ch 11 **ANCHORED**, mechanism **PARTIAL** O1-1). Superposition = photon mid-bounce in z before polarizer pins axis.'
));

children.push(H2('4.5  pi/complex_walker — Same Recurrence, No Trig Library'));

children.push(PR(
  'The π engine builds rotation operators R_k from (A_k, C_k) without importing cos/sin. The 3D plane at triggers and complex_walker on the unit circle are one recurrence in two views — Ch 1 §1.7 triangles-not-trig made executable.'
));

children.push(PREDICTION(
  'Degeneracy: find_same_n_collisions reports multiple wings at one coordinate — testable as collision counting in lattice_id scans.'
));

children.push(PAGEBREAK());

// =====================================================================
// CHAPTER 5
// =====================================================================
children.push(H1('Chapter 5: Meets, Triggers, and the Hilbert Stack'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { line: 360, after: 0 },
    children: [new TextRun({
      text: 'Trigger nodes fire at anchor crossings. Meet rules glue banks without messaging. The Hilbert layering in derivations/hilbert_space.md is the formal direct-sum picture of this geometry.',
      size: 22, italics: true, font: 'Georgia',
    })],
  }),
]));

children.push(H2('5.1  Trigger Nodes'));

children.push(PR(
  'TriggerNode.at(chain, n): each n = a_i on the chain is a spring bounce event. trigger_history yields (a_i, Ψ) prime-by-prime — the inner photon\'s ledger of crossings. This is the operational clock underneath abstract iteration depth k (Ch 18 lattice clock).'
));

children.push(H2('5.2  Two-Way Meet — Swap'));

children.push(PR(
  'swap_meet(a, p): solo chain {a} at n = p vs solo {p} at n = a land on the ',
  { text: 'same', bold: true },
  ' coordinate (all 32 wings tested for integral chains). Example: swap_meet(3,5) → z = 8 + 3i both ways. **MODEL** entanglement: mirror banks equalize without a signal — preview of Ch 12 Bell geometry.'
));

children.push(...DIAGRAM([
  '',
  '   bank(a) @ n=p  ═══════════  bank(p) @ n=a',
  '         │                              │',
  '         └──────── same (X,Y,ζ) ────────┘',
  '',
  '   Different paths; one geometric node (meet quotient).',
  '',
], 'Figure 5.1: Solo swap meet.'));

children.push(H2('5.3  k-Way Equalization'));

children.push(PR(
  'For chain A = (a, p, q) sorted, missing-variable rule: transgress subset S until n equals the missing anchor. triple_equalization(3,5,7) yields one shared node from three 2-way rails — witnesses n = 7, 5, 3 respectively. Same coordinate, distinct Hilbert labels if path/branch/wing differ.'
));

children.push(H2('5.4  Same Node, Different State'));

children.push(PR(
  'Meet quotient: |ψ₁⟩ ~ |ψ₂⟩ when coords collide, but path (which anchors, which branch b, which wing w, trigger history) can differ. **Physics:** Bell correlation without controllable message — global constraint, local labels (C5). Interior ζ lock: bulk subspace where depth frozen — **MODEL** photon sea (Ch 1 §1.4, Ch 17 dark sector).'
));

children.push(H2('5.5  Hilbert Layer Stack (Summary)'));

children.push(BULLET('Layer 0: ℝ³ embedding per (chain, n, wing).'));
children.push(BULLET('Layer 1: ⊕₃₂ wing subspaces per bank.'));
children.push(BULLET('Layer 2: ⊕_{k+1} segment sectors (boundary vs interior).'));
children.push(BULLET('Layer 3: ⊕₄ branch phases per segment.'));
children.push(BULLET('Layer 4–6: permutation fiber, origin tree, species direct sum.'));
children.push(BULLET('Layer 7: meet quotient → physical state space.'));
children.push(BULLET('Layer 8: token ℓ² on primes (sparse semantic layer).'));

children.push(PR(
  'Cosmic hierarchy (Ch 19 gravity sync) is the same pattern at larger scales: nested clocks, each a direct sum of synchronized chambers — **MODEL** scale analogy, not derived from Layer 8 alone.'
));

children.push(H2('5.6  What Particles Do Here'));

children.push(PR(
  'A particle does not solve for Ψ. It ',
  { text: 'occupies', bold: true },
  ' one α at a time, advancing n and firing triggers when anchors are crossed. The 3D complex plane is the chart on which that motion is recorded. Mathematics (Hilbert spaces, cos, sin) compresses the chart; the chart is the mechanism.'
));

children.push(OPEN_Q(
  'Full functor from π addresses to (A,b,w,n)?',
  'PARTIAL — proven bridges at layer 0 and i_act; demo maps for depth and ±B bits; canon_on_chain = pi walker for all chains still OPEN.'
));

children.push(PREDICTION(
  'Meet-node coordinates should be stable under wing sweep; branch fan breaks degeneracy — reproduce swap_meet and triple_equalization in any port of the codebase.'
));

children.push(PAGEBREAK());

// =====================================================================
// CHAPTER 6
// =====================================================================
children.push(H1('Chapter 6: The 3D Complex Plane — Unbounded Extension'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { line: 360, after: 0 },
    children: [new TextRun({
      text: 'The 3D complex plane extends without bound: n → ∞, k → ∞, origin depth → ∞, countable species direct sum. "Infinity" names extension — not a separate "infinity lattice." The plane is Ψ=(z,ζ); the lattice formula generates it.',
      size: 22, italics: true, font: 'Georgia',
    })],
  }),
]));

children.push(H2('6.1  What “True 3D” Means'));

children.push(PR(
  'A flat Argand diagram is 2D — a flat sheet, not the arena. The lattice particles play in is ',
  { text: 'Ψ = (z, ζ) ∈ ℂ × ℝ', bold: true },
  ': spring plane z = X + iY plus depth ζ along the anchor rail. That pair ',
  { text: 'is', italics: true },
  ' three-dimensional space: two spring axes (Re z, Im z) plus depth. Plotting (Re z, Im z, ζ) in ℝ³ is one camera on one wing at one instant — not a container behind the lattice. The ',
  { text: 'full', bold: true },
  ' space = direct sums and tensor products over wings, segments, branches, permutations, origins, and species (**DERIVED** aethos_hilbert.py) — all of it still the same lattice, not a separate Hilbert abstraction floating above reality (**MODEL** reading of completion).'
));

children.push(H2('6.2  Three Infinity Directions'));

children.push(BULLET('n → ∞ — transgressor never terminates; infinitely many segment visits along each wing (**DERIVED**).'));
children.push(BULLET('k → ∞ — extend anchor chain countably; new segments and plateau structure (**DERIVED**).'));
children.push(BULLET('depth → ∞ — origin tree: each meet spawns 3 child rooms (D1, D2, D3); 3^d rooms at depth d (**DERIVED** aethos_origins.py).'));

children.push(EQ_NUM('H_{\\mathrm{total}} \\supset \\bigoplus_{\\mathrm{species}} H_{\\mathrm{species}} \\supset \\bigotimes_{\\mathrm{rooms}} H_{\\mathrm{bank}}', '6.1'));

children.push(PR(
  'Finite windows (demo): estimate_hilbert_tower(chain_k, n_max, origin_depth) counts truncated basis size — millions in modest windows; full space is ',
  { text: 'infinite-dimensional separable', bold: true },
  ' (**DERIVED**; Cauchy completion in label topology — **MODEL** physics reading).'
));

children.push(...DIAGRAM([
  '',
  '   INFINITY CAPABILITY (three directions)',
  '',
  '   n ─────────────────────────────►  (transgressor rail)',
  '   k ──► a₁, a₂, a₃, ...           (extend anchor set)',
  '   d ──► room ──► 3 children ──► 3 children ...  (origin tree)',
  '',
  '   At EVERY node: 4 branches × 8 wings = 32 chambers in ℂ×ℝ',
  '',
], 'Figure 6.1: Unbounded n, k, and origin depth.'));

children.push(H2('6.3  Origin Tree — Rooms Inside Rooms'));

children.push(PR(
  'OriginTree.bootstrap(species, chain_len, max_depth): root hosts 32 wings; when branches ',
  { text: 'meet', bold: true },
  ', a new origin spawns with three child dimension-slots (D1, D2, D3). Each child is a full new room in the ',
  { text: 'same', italics: true },
  ' lattice — same formula family, offset by parent meet coordinate. Depth 3 → 40 origins; depth 5 → 364 origins (**PROVEN** test_origin_count). "No fixed ℝ³ box" means space is not a single finite Cartesian cube with the lattice drawn inside; the lattice ',
  { text: 'is', bold: true },
  ' space, and depth can nest without bound (**MODEL** cosmic nesting, Ch 19).'
));

children.push(EQ_NUM('\\text{origins(depth } d) = \\text{geometric\_origin\_count}(d) \\quad (e.g.\\ 364 \\text{ at } d=5)', '6.2'));

children.push(H2('6.4  Species-Dependent Planes'));

children.push(PR(
  'Choosing SequenceKind selects which anchor template feeds the plane formula. Same n, different kind → different Ψ on the same 3D complex plane machinery. Extend k without bound: primes forever, evens forever, etc. CUSTOM chains for physics-chosen schedules (**MODEL**).'
));

children.push(H2('6.5  Permutation Fiber and Path History'));

children.push(PR(
  'Sorted multiset gives anchor ',
  { text: 'content', italics: true },
  '; permutation order gives ',
  { text: 'path', italics: true },
  '. Fiber dimension k! (capped in demos) — orthogonal labels for history even when (X,Y,ζ) collide. Hilbert inner product: different permutations → orthogonal unless meet identifies (**DERIVED** hilbert_space.md Layer 4).'
));

children.push(H2('6.6  Completeness — Why This Is a “Full” Plane'));

children.push(PR(
  'Separability: every state has a ',
  { text: 'finite', bold: true },
  ' label (origin_id, wing, chain prefix, n, branch, perm_index, species). Countably many labels → separable Hilbert space. Completeness: meet quotient + segment continuity define limits; truncated windows approximate (**MODEL** link to QM completeness).'
));

children.push(EQ_NUM('|\\mathrm{basis}|_{\\mathrm{window}} \\sim \\mathrm{origins} \\times 32 \\times n_{\\max} \\times 4 \\times k! \\times |\\mathrm{species}|', '6.3'));

children.push(H2('6.7  Construction Recipe (Executable)'));

children.push(NUMBERED('Pick species kind → make_chain(kind, k) → anchor set A.'));
children.push(NUMBERED('Pick branch b ∈ {VA1..VA4}, wing w ∈ {1..8}, transgressor n.'));
children.push(NUMBERED('Evaluate wing_transform(b, A, n, w) → Ψ = (z, ζ) ∈ ℂ × ℝ.'));
children.push(NUMBERED('On anchor crossing: record trigger_history; on meet: extend chain, spawn Origin children.'));
children.push(NUMBERED('Extend k, n, depth without bound → unbounded 3D complex plane on chosen species.'));

children.push(PR(
  'This recipe ',
  { text: 'is', bold: true },
  ' how particles traverse physical space: every bounce is a labeled move in (A, b, w, n) with origin-tree nesting when meets fire. π unit-circle (Ch 2) is the bisection shadow at high refinement — still the same lattice seen from the unit-circle gate. Ψ = (z, ζ) is the spring-native coordinate system of the arena itself.'
));

children.push(OPEN_Q(
  'Unique physical inner product without token layer?',
  'OPEN — robust inner product adds geometric + meet + correlation weights (aethos_hilbert_lattice.py).'
));

children.push(PREDICTION(
  'origin_depth=5 → 364 rooms × 32 wings; wing compute all origins under 30s (test suite) — scaling predicts hardware limits before physics limits.'
));

children.push(PAGEBREAK());

// =====================================================================
// CHAPTER 7
// =====================================================================
children.push(H1('Chapter 7: SequenceKind — Worked Examples'));

children.push(BOX([
  new Paragraph({
    alignment: AlignmentType.CENTER, spacing: { line: 360, after: 0 },
    children: [new TextRun({
      text: 'Same engine (VA1–VA4, 32 wings), different infinite set A — different geometry. This chapter compares species side-by-side at matched transgressor n. Values from aethos_sequences.canon_on_chain / wing_transform (wing 1, branch VA1, k=5).',
      size: 22, italics: true, font: 'Georgia',
    })],
  }),
]));

children.push(H2('7.1  The Species Selector'));

children.push(PR(
  'Call ',
  { text: 'make_chain(kind, k)', bold: true },
  ' to materialize the first k anchors. The kind fixes which anchor template on the 3D complex plane. Changing kind at fixed n changes (X, Y, ζ) and therefore z and ζ — **PROVEN** (test_different_species_differ_at_same_n).'
));

children.push(BULLET('PRIMES — (3, 5, 7, 11, 13, …) odd primes; anchor 2 skipped.'));
children.push(BULLET('EVENS — (2, 4, 6, 8, …) uniform spacing.'));
children.push(BULLET('POWERS_OF_2 — (2, 4, 8, 16, …) exponential spacing.'));
children.push(BULLET('SQUARES — (1, 4, 9, 16, …); TRIPLES — (3, 6, 9, …).'));
children.push(BULLET('SQRT_SCALED — integer ladder approximating √k; CUSTOM — any strictly increasing normalize_chain input.'));
children.push(PR(
  'FIBONACCI is listed in code but early terms repeat (1, 1, …) and fail strict-increase validation — use deduplicated CUSTOM chain for Fibonacci physics trials (**OPEN** generator fix).'
));

children.push(H2('7.2  Five Species at k = 5 — Same n, Different Ψ'));

children.push(PR('Anchor chains (k = 5):'));

children.push(...DIAGRAM([
  '',
  '   PRIMES      (3, 5, 7, 11, 13)     sum(A) = 39',
  '   EVENS       (2, 4, 6, 8, 10)      sum(A) = 30',
  '   POWERS_2    (2, 4, 8, 16, 32)     sum(A) = 62',
  '   SQUARES     (1, 4, 9, 16, 25)     sum(A) = 55',
  '   TRIPLES     (3, 6, 9, 12, 15)     sum(A) = 45',
  '',
], 'Table 7.1: Anchor chains for comparison runs.'));

children.push(PR('VA1, wing w = 1, matched transgressor n = 10:'));

children.push(...DIAGRAM([
  '',
  '   Species     n   seg   X      Y      ζ      |z|^2',
  '   ─────────────────────────────────────────────────',
  '   PRIMES     10    3   23     10     39      629',
  '   EVENS      10    5   20     10     40      500',
  '   POWERS_2   10    3   42     10     62     1864',
  '   SQUARES    10    3   35     10     55     1325',
  '   TRIPLES    10    3   25     10     45      725',
  '',
], 'Table 7.2: Same n = 10 — different species, different spring readout.'));

children.push(PR(
  'At the ',
  { text: 'same', italics: true },
  ' lab transgressor n, spring plane position and depth ζ differ by species. |z|² tracks spring intensity (Born envelope **PARTIAL**). This is what “the set defines the lattice” means operationally.'
));

children.push(H2('7.3  Segment Schedule — When ζ Locks'));

children.push(PR(
  'Segment index s = segment_index(A, n) counts how many anchors n has passed. Interior plateau (k ≥ 3, 0 < s < k): ζ = sum(A) only — depth frozen while X,Y move. Example PRIMES k=5: n = 7, 10 → ζ = 39; n = 13 (past final anchor) → ζ = 52 = 39 + 13.'
));

children.push(...DIAGRAM([
  '',
  '   PRIMES  n:   3     5     7    10    13',
  '          seg:  1     2     3     3     5',
  '          ζ:   39    39    39    39    52',
  '',
  '   EVENS   n:   3     5     7    10    13',
  '          seg:  1     2     3     5     5',
  '          ζ:   30    30    30    40    43',
  '',
], 'Table 7.3: Segment and depth vs n — species change plateau width and unlock timing.'));

children.push(H2('7.4  Full Row Scan (VA1, wing 1)'));

children.push(...DIAGRAM([
  '',
  '   n=5:',
  '   PRIMES    (18, 5, 39)   EVENS     (15, 5, 30)   POWERS_2  (37, 5, 62)',
  '   SQUARES   (30, 5, 55)   TRIPLES   (20, 5, 45)',
  '',
  '   n=7:',
  '   PRIMES    (20, 7, 39)   EVENS     (17, 7, 30)   POWERS_2  (39, 7, 62)',
  '',
], 'Table 7.4: Matched n snapshots (executable canon_on_chain).'));

children.push(H2('7.5  Physics Readings (MODEL)'));

children.push(BULLET('PRIMES — default electron / vacuum addressing in tests; sparse anchor crossings.'));
children.push(BULLET('EVENS — uniform compression schedule; analogue to evenly spaced resonances.'));
children.push(BULLET('POWERS_2 — wide ζ jumps; steep interior; model for hierarchical doubling (shells, binary addressing).'));
children.push(BULLET('SQUARES / TRIPLES — polynomial ladders; model for orbital / shell quantum numbers (**MODEL**, not fitted here).'));
children.push(BULLET('CUSTOM — nuclear or astrophysical ladder chosen by physics, fed to normalize_chain — **MODEL** application path.'));

children.push(H2('7.6  Extending k — Same Kind, Longer Infinite Template'));

children.push(PR(
  'Increasing k appends anchors without changing the generator rule: PRIMES forever, EVENS forever, etc. Segment count becomes k+1; interior plateau widens. Hilbert tower estimate scales species_count × origins × 32 × n_max × 4 × k! (**DERIVED** estimate_hilbert_tower). The ',
  { text: 'infinite', italics: true },
  ' lattice is one kind plus k → ∞.'
));

children.push(EQ_NUM('A^{(k)} = \\mathrm{make\\_chain}(\\mathrm{kind}, k) \\;\\Rightarrow\\; A^{(k+1)} \\supset A^{(k)}', '7.1'));

children.push(H2('7.7  Runnable Recipe'));

children.push(...DIAGRAM([
  '',
  '   from aethos_sequences import make_chain, SequenceKind',
  '   from aethos_complex_plane import wing_transform',
  '   from aethos_lattice import BranchKind',
  '',
  '   A = make_chain(SequenceKind.PRIMES, 5)',
  '   psi = wing_transform(BranchKind.VA1, A, n=10, wing=1)',
  '   # psi.z, psi.zeta  ->  Table 7.2 PRIMES row',
  '',
], 'Listing 7.1: Reproduce Table 7.2 in Python.'));

children.push(PREDICTION(
  'Species discriminator: same experimental n, swap only SequenceKind in simulation — predict distinct fringe/coherence envelopes if species couples to environment (**MODEL**; no lab protocol yet).'
));

children.push(OPEN_Q(
  'Fix FIBONACCI strict-increase (dedupe or offset rule)?',
  'OPEN — use CUSTOM (1,2,3,5,8,…) until generator patched.'
));

children.push(PAGEBREAK());

(async () => {
  const doc = buildDoc('3-7', 'Chapters 3–7 — The 3D Complex Plane', children);
  await saveDoc(doc, 'book/output/03_ThreeD_Complex_Plane.docx');
})().catch((err) => {
  console.error(err);
  process.exit(1);
});
